include ../../Makefile.inc

all:
	cp ../../lua-544/lapi.s .
	cp ../../lua-544/lctype.s .
	cp ../../lua-544/ldebug.s .
	cp ../../lua-544/ldo.s .
	cp ../../lua-544/ldump.s .
	cp ../../lua-544/lfunc.s .
	cp ../../lua-544/lgc.s .
	cp ../../lua-544/lmem.s .
	cp ../../lua-544/lobject.s .
	cp ../../lua-544/lopcodes.s .
	cp ../../lua-544/lstate.s .
	cp ../../lua-544/lstring.s .
	cp ../../lua-544/ltable.s .
	cp ../../lua-544/ltm.s .
	cp ../../lua-544/lundump.s .
	cp ../../lua-544/lvm.s .
	cp ../../lua-544/lzio.s .
	cp ../../lua-544/lauxlib.s .
	cp ../../lua-544/lbaselib.s .
	cp ../../lua-544/lcorolib.s .
	cp ../../lua-544/ldblib.s .
	cp ../../lua-544/liolib.s .
	cp ../../lua-544/lmathlib.s .
	cp ../../lua-544/loadlib.s .
	cp ../../lua-544/loslib.s .
	cp ../../lua-544/lstrlib.s .
	cp ../../lua-544/ltablib.s .
	cp ../../lua-544/lutf8lib.s .
	cp ../../lua-544/luathreads.s .
	cp ../../lua-544/luathreadsched.s .
	cp ../../lua-544/luapropeller.s .
	cp ../../lua-544/storage.s .
	cp ../../lua-544/glob.s .
	cp ../../lua-544/catalina_fgets.s .
	build_index

clean:
	-rm -f *.s catalina.idx



