include ../../Makefile.inc

all:
	cp ../../float/float_a.s .
	cp ../../float/fplugin.s .
	cp ../../float/fservice.s .
	cp ../../float/lround.s .
	cp ../../float/ltrunc.s .
	cp ../../float/fround.s .
	cp ../../float/ftrunc.s .
	cp ../../math/fmod.s .
	cp ../../math/isinf.s .
	cp ../../math/isnan.s .
	cp ../../math/fpclass.s .
	cp ../../math/ldexp.s .
	cp ../../math/frexp.s .
	cp ../../math/hugeval.s .
	cp ../../math/fabs.s .
	cp ../../math/sinh.s .
	cp ../../math/tanh.s .
	cp ../../math/asin.s .
	cp ../../math/atan.s .
	cp ../../math/atan2.s .
	cp ../../math/ceil.s .
	cp ../../math/floor.s .
	build_index

clean:
	-rm -f *.s catalina.idx

