include ../../Makefile.inc

all:
	cp ../../float/lround.s .
	cp ../../float/ltrunc.s .
	cp ../../float/fround.s .
	cp ../../float/ftrunc.s .
	cp ../../math/*.s .
	build_index

clean:
	-rm -f *.s catalina.idx

