include ../../Makefile.inc

all:
	cp ../../lua/lapi.s .
	cp ../../lua/lctype.s .
	cp ../../lua/ldebug.s .
	cp ../../lua/ldo.s .
	cp ../../lua/ldump.s .
	cp ../../lua/lfunc.s .
	cp ../../lua/lgc.s .
	cp ../../lua/lmem.s .
	cp ../../lua/lobject.s .
	cp ../../lua/lopcodes.s .
	cp ../../lua/lstate.s .
	cp ../../lua/lstring.s .
	cp ../../lua/ltable.s .
	cp ../../lua/ltm.s .
	cp ../../lua/lundump.s .
	cp ../../lua/lvm.s .
	cp ../../lua/lzio.s .
	cp ../../lua/lauxlib.s .
	cp ../../lua/lbaselib.s .
	cp ../../lua/lcorolib.s .
	cp ../../lua/ldblib.s .
	cp ../../lua/liolib.s .
	cp ../../lua/lmathlib.s .
	cp ../../lua/loadlib.s .
	cp ../../lua/loslib.s .
	cp ../../lua/lstrlib.s .
	cp ../../lua/ltablib.s .
	cp ../../lua/lutf8lib.s .
	cp ../../lua/lthreads.s .
	cp ../../lua/lthrsch.s .
	cp ../../lua/lprop.s .
	cp ../../lua/lhmi.s .
	cp ../../lua/lservice.s .
	cp ../../lua/lserial.s .
	cp ../../lua/lwifi.s .
	cp ../../lua/storage.s .
	cp ../../lua/glob.s .
	cp ../../lua/cfgets.s .
	build_index

clean:
	-rm -f *.s catalina.idx



