import p2
import p2ipc

var ch = p2.channel.new(2)

var caps = p2ipc.capabilities()
var contract = p2ipc.contract()
var self_test = p2ipc.self_test_result(1)
var info = ch.info()
print("p2ipc channel capabilities:", caps["channel"], caps["mailbox"], caps["shared_buffer"], caps["payload_contract_results"])
print("p2ipc contract:", contract["model"], contract["current_vm"], contract["cross_vm"], contract["serialization_policy"])
print("p2ipc self test:", self_test["ok"], self_test["iterations"], self_test["failure_count"])
print("channel info:", info["kind"], info["depth"], info["size"], info["free"], info["closed"])

var first = ch.send_result("alpha")
var second = ch.send_result("beta")
var full = ch.send_result("gamma")

print("send alpha:", first["ok"], first["size"], first["free"])
print("send alpha payload contract:", first["payload_contract"], first["ownership_policy"])
print("send beta:", second["ok"], second["size"], second["free"])
print("send gamma while full:", full["ok"], full["error"], full["size"], full["free"])
var snapshot = ch.snapshot_result()
print("channel snapshot:", snapshot["ok"], snapshot["items"].size(), snapshot["payload_contract"])

var recv_first = ch.recv_result()
var recv_second = ch.recv_result()
var recv_empty = ch.recv_result()
print("recv first:", recv_first["ok"], recv_first["found"], recv_first["value"])
print("recv second:", recv_second["ok"], recv_second["found"], recv_second["value"])
print("recv empty:", recv_empty["ok"], recv_empty["found"])

var cleanup = ch.send_result("cleanup")
var clear_ch = ch.clear_result()
var retained = ch.send_result("retained")
var close_ch = ch.close_result()
var after_close = ch.send_result("after-close")
print("send cleanup payload:", cleanup["ok"], cleanup["size"])
print("clear channel:", clear_ch["ok"], clear_ch["released_payloads"])
print("send retained payload:", retained["ok"], retained["size"])
print("close:", close_ch["ok"], close_ch["closed"], close_ch["released_payloads"])
print("send after close:", after_close["ok"], after_close["error"])

var mb = p2.mailbox.new()
var mb_put = mb.put_result("message")
var mb_peek = mb.peek_result()
var mb_clear = mb.clear_result()
var mb_close = mb.close_result()
print("mailbox put:", mb_put["ok"], mb_put["stored"], mb_put["ready"])
print("mailbox peek:", mb_peek["ok"], mb_peek["found"], mb_peek["value"])
print("mailbox clear:", mb_clear["ok"], mb_clear["released_payload"])
print("mailbox close:", mb_close["ok"], mb_close["closed"])

var buf = p2.shared.Buffer(4)
var fill = buf.fill_result(7)
var clear_buf = buf.clear_result()
print("buffer fill:", fill["ok"], fill["filled"])
print("buffer clear:", clear_buf["ok"], clear_buf["released_bytes"])
print("cog channel example done")
