import p2

print("P2 debug snapshot:")
var snapshot = p2.debug.snapshot()
var heap = p2.debug.heap()
var gc = p2.debug.gc()
var cogs = p2.debug.cogs()
var memory = p2.debug.memory_map()
var caps = p2.debug.capabilities()
var fs = p2.fs_info()
var psram = p2.psram_info()
print("profile:", snapshot["build"]["profile"])
print("led pin:", snapshot["build"]["led0_pin"])
print("cog count:", cogs.size())
print("heap current:", heap["current"])
print("gc after:", gc["after"])
print("hub total:", memory["hub_total"])
print("fs mounted:", fs["mounted"])
print("psram available:", psram["available"])
print("debug snapshots:", caps["snapshot"], caps["heap"], caps["registers"])
print("debug controls:", caps["breakpoints"], caps["trace_controls"])
print("debug policy:", caps["policy"])
print("debug report done")
