import task

var q = task.Queue(2)
var put_alpha = q.put_result("alpha")
var put_nil = q.put_result(nil)
var put_full = q.put_result("gamma")
print("queue put alpha:", put_alpha["ok"], put_alpha["size"], put_alpha["free"])
print("queue put nil:", put_nil["ok"], put_nil["size"], put_nil["free"])
print("queue full:", put_full["ok"], put_full["error"], put_full["size"], put_full["free"])
var get_alpha = q.get_result(nil)
var get_nil = q.get_result(nil)
var get_empty = q.get_result(nil)
print("queue get:", get_alpha["ok"], get_alpha["value"], get_alpha["size"], get_alpha["free"])
print("queue get nil payload:", get_nil["ok"], get_nil["value"], get_nil["size"], get_nil["free"])
print("queue empty:", get_empty["ok"], get_empty["error"])

var flags = task.EventFlags(0)
var flags_set = flags.set_result(0x03)
var flags_ready_all = flags.ready_result(0x03, "all")
var flags_ready_missing = flags.ready_result(0x04, "any")
var flags_clear = flags.clear_result(0x01)
print("flags set:", flags_set["ok"], flags_set["value"])
print("flags ready all:", flags_ready_all["ok"], flags_ready_all["ready"])
print("flags ready missing:", flags_ready_missing["ok"], flags_ready_missing["error"])
print("flags clear:", flags_clear["ok"], flags_clear["value"])

var timer = task.Timer(0, false)
var timer_remaining = timer.remaining_result()
var timer_expired = timer.expired_result()
var timer_expired_again = timer.expired_result()
var timer_restart = timer.restart_result()
var timer_remaining_restart = timer.remaining_result()
var timer_cancel = timer.cancel_result()
print("timer remaining:", timer_remaining["ok"], timer_remaining["remaining_ms"])
print("timer expired:", timer_expired["ok"], timer_expired["expired"], timer_expired["active"])
print("timer expired again:", timer_expired_again["ok"], timer_expired_again["expired"], timer_expired_again["active"])
print("timer restart:", timer_restart["ok"], timer_restart["active"])
print("timer remaining after restart:", timer_remaining_restart["ok"], timer_remaining_restart["remaining_ms"])
print("timer cancel:", timer_cancel["ok"], timer_cancel["active"])
print("task primitives example done")
