import introspect

def expect_error(fn)
    var caught = false
    try
        fn()
    except .. as e, m
        caught = true
    end
    assert(caught)
end

var p2 = module("p2")
var lock = module("p2.lock")
var lock_state = {}
var next_lock = 0

lock.new = def()
    var id = next_lock
    next_lock += 1
    lock_state[id] = false
    return id
end
lock.("try") = def(id)
    if lock_state[id]
        return 0
    end
    lock_state[id] = true
    return 1
end
lock.release = def(id)
    lock_state[id] = false
end
lock.ret = def(id)
    lock_state.remove(id)
end

p2.lock = lock
introspect.setmodule("p2", p2)

var p2ipc = run_file("modules/p2ipc.be")
assert(type(p2ipc) == "module")
assert(type(p2.channel) == "module")
assert(type(p2.mailbox) == "module")
assert(type(p2.shared) == "module")
assert(type(p2.mutex) == "module")
assert(type(p2ipc.capabilities) == "function")
assert(type(p2ipc.capability) == "function")
assert(type(p2ipc.contract) == "function")
assert(type(p2ipc.attention_policy) == "function")
assert(type(p2ipc.cross_cog_channel_policy) == "function")
assert(type(p2ipc.cross_cog_channel) == "function")
assert(type(p2ipc.required_capability_keys) == "function")
assert(type(p2ipc.required_contract_keys) == "function")
assert(type(p2ipc.audit) == "function")
assert(type(p2ipc.audit_problems) == "function")
assert(type(p2ipc.audit_ok) == "function")
assert(type(p2ipc.self_test_result) == "function")
assert(type(p2ipc.lifecycle_result) == "function")
assert(type(p2ipc.payload_result) == "function")
var caps = p2ipc.capabilities()
assert(caps["current_vm"])
assert(!caps["cross_vm"])
assert(caps["contract"])
assert(!caps["cross_cog_channel"])
assert(caps["cross_cog_channel_policy"])
assert(caps["wakeup_policy"] == "no_cross_cog_wakeup")
assert(caps["attention_policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(!caps["bounded_attention_wait"])
assert(!caps["cross_cog_attention_wakeup"])
assert(caps["serialization_policy"] == "unsupported_current_vm_references_only")
assert(caps["ownership_policy"] == "caller_keeps_current_vm_object_ownership")
assert(caps["payload_contract_results"])
assert(caps["payload_result"])
assert(!caps["payload_copyable_probe"])
assert(caps["payload_copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(caps["task_wait_integration"])
assert(caps["task_wait_channel"])
assert(caps["task_wait_mailbox"])
assert(caps["channel"])
assert(caps["mailbox"])
assert(caps["mutex"])
assert(caps["shared_buffer"])
assert(caps["result_diagnostics"])
assert(caps["nil_payload_results"])
assert(caps["close_result"])
assert(caps["close_releases_payloads"])
assert(caps["clear_result"])
assert(caps["clear_releases_payloads"])
assert(caps["lifecycle_result"])
assert(caps["resource_lifecycle_result"])
assert(caps["readiness_result"])
assert(caps["channel_ready_result"])
assert(caps["mailbox_ready_result"])
assert(caps["snapshot_result"])
assert(caps["peek_result"])
assert(caps["shared_buffer_clear_result"])
assert(caps["self_test_result"])
assert(caps["self_test_policy"] == "bounded_current_vm_cleanup_diagnostic")
assert(caps["hardware_lock_backend_available"])
assert(caps["fallback_mutex"])
caps["channel"] = false
assert(p2ipc.capabilities()["channel"])
assert(p2ipc.capability("channel"))
assert(p2ipc.capability("cross_vm") == false)
assert(p2ipc.capability("contract"))
assert(p2ipc.capability("cross_cog_channel") == false)
assert(p2ipc.capability("cross_cog_channel_policy"))
assert(p2ipc.capability("attention_policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.capability("task_wait_integration"))
assert(p2ipc.capability("serialization_policy") == "unsupported_current_vm_references_only")
assert(p2ipc.capability("payload_result"))
assert(p2ipc.capability("payload_copy_policy") == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(p2ipc.capability("missing") == nil)
assert(p2ipc.capability(nil) == nil)
var required_caps = p2ipc.required_capability_keys()
assert(required_caps.find("cross_cog_channel") >= 0)
assert(required_caps.find("cross_cog_channel_policy") >= 0)
assert(required_caps.find("serialization_policy") >= 0)
assert(required_caps.find("attention_policy") >= 0)
assert(required_caps.find("bounded_attention_wait") >= 0)
assert(required_caps.find("cross_cog_attention_wakeup") >= 0)
assert(required_caps.find("payload_contract_results") >= 0)
assert(required_caps.find("payload_result") >= 0)
assert(required_caps.find("payload_copyable_probe") >= 0)
assert(required_caps.find("payload_copy_policy") >= 0)
assert(required_caps.find("task_wait_integration") >= 0)
assert(required_caps.find("task_wait_channel") >= 0)
assert(required_caps.find("task_wait_mailbox") >= 0)
assert(required_caps.find("lifecycle_result") >= 0)
assert(required_caps.find("resource_lifecycle_result") >= 0)
assert(required_caps.find("readiness_result") >= 0)
assert(required_caps.find("channel_ready_result") >= 0)
assert(required_caps.find("mailbox_ready_result") >= 0)
assert(required_caps.find("self_test_policy") >= 0)
required_caps.push("mutated")
assert(p2ipc.required_capability_keys().find("mutated") == nil)
var contract = p2ipc.contract()
assert(contract["model"] == "current_vm_cooperative_ipc")
assert(contract["current_vm"])
assert(!contract["cross_vm"])
assert(!contract["cross_cog_channel"])
assert(contract["cross_cog_channel_policy"] == "unsupported_no_cross_cog_wakeup_or_serialization")
assert(!contract["cross_cog_wakeup"])
assert(!contract["serialization"])
assert(!contract["ownership_transfer"])
assert(contract["payload_contract_results"])
assert(contract["payload_result"])
assert(!contract["payload_copyable_probe"])
assert(contract["payload_copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(contract["task_wait_integration"])
assert(contract["task_wait_channel"])
assert(contract["task_wait_mailbox"])
assert(contract["close_releases_payloads"])
assert(contract["clear_releases_payloads"])
assert(contract["lifecycle_result"])
assert(contract["resource_lifecycle_result"])
assert(contract["readiness_result"])
assert(contract["channel_ready_result"])
assert(contract["mailbox_ready_result"])
assert(contract["snapshot_result"])
assert(contract["peek_result"])
assert(contract["shared_buffer_clear_result"])
assert(contract["self_test_result"])
assert(contract["self_test_policy"] == "bounded_current_vm_cleanup_diagnostic")
assert(contract["hardware_lock_backend_available"])
assert(contract["fallback_mutex"])
assert(contract["wakeup_policy"] == "no_cross_cog_wakeup")
assert(contract["attention_policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(!contract["bounded_attention_wait"])
assert(!contract["cross_cog_attention_wakeup"])
assert(contract["serialization_policy"] == "unsupported_current_vm_references_only")
assert(contract["ownership_policy"] == "caller_keeps_current_vm_object_ownership")
assert(type(p2ipc.contract_value) == "function")
assert(p2ipc.contract_value("model") == "current_vm_cooperative_ipc")
assert(p2ipc.contract_value("current_vm"))
assert(p2ipc.contract_value("cross_vm") == false)
assert(p2ipc.contract_value("cross_cog_channel") == false)
assert(p2ipc.contract_value("cross_cog_channel_policy") == "unsupported_no_cross_cog_wakeup_or_serialization")
assert(p2ipc.contract_value("task_wait_integration"))
assert(p2ipc.contract_value("attention_policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.contract_value("serialization_policy") == "unsupported_current_vm_references_only")
assert(p2ipc.contract_value("payload_result"))
assert(p2ipc.contract_value("payload_copy_policy") == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(p2ipc.contract_value("missing") == nil)
assert(p2ipc.contract_value(nil) == nil)
contract["cross_vm"] = true
assert(!p2ipc.contract()["cross_vm"])
var required_contract = p2ipc.required_contract_keys()
assert(required_contract.find("cross_cog_channel") >= 0)
assert(required_contract.find("cross_cog_channel_policy") >= 0)
assert(required_contract.find("ownership_transfer") >= 0)
assert(required_contract.find("task_wait_integration") >= 0)
assert(required_contract.find("task_wait_channel") >= 0)
assert(required_contract.find("task_wait_mailbox") >= 0)
assert(required_contract.find("lifecycle_result") >= 0)
assert(required_contract.find("resource_lifecycle_result") >= 0)
assert(required_contract.find("readiness_result") >= 0)
assert(required_contract.find("channel_ready_result") >= 0)
assert(required_contract.find("mailbox_ready_result") >= 0)
assert(required_contract.find("attention_policy") >= 0)
assert(required_contract.find("bounded_attention_wait") >= 0)
assert(required_contract.find("cross_cog_attention_wakeup") >= 0)
assert(required_contract.find("unsupported_reason") >= 0)
assert(required_contract.find("payload_result") >= 0)
assert(required_contract.find("payload_copyable_probe") >= 0)
assert(required_contract.find("payload_copy_policy") >= 0)
required_contract.push("mutated")
assert(p2ipc.required_contract_keys().find("mutated") == nil)
var audit = p2ipc.audit()
assert(audit["ok"])
assert(audit["problem_count"] == 0)
assert(audit["problems"].size() == 0)
assert(audit["model"] == "current_vm_cooperative_ipc")
assert(audit["current_vm"])
assert(!audit["cross_vm"])
assert(!audit["cross_cog_channel"])
assert(audit["cross_cog_channel_policy"] == "unsupported_no_cross_cog_wakeup_or_serialization")
assert(!audit["cross_cog_attention_wakeup"])
assert(!audit["bounded_attention_wait"])
assert(!audit["serialization"])
assert(!audit["ownership_transfer"])
assert(audit["payload_contract_results"])
assert(audit["payload_result"])
assert(!audit["payload_copyable_probe"])
assert(audit["payload_copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(audit["task_wait_integration"])
assert(audit["task_wait_channel"])
assert(audit["task_wait_mailbox"])
assert(audit["lifecycle_result"])
assert(audit["resource_lifecycle_result"])
assert(audit["readiness_result"])
assert(audit["channel_ready_result"])
assert(audit["mailbox_ready_result"])
assert(audit["snapshot_result"])
assert(audit["peek_result"])
assert(audit["self_test_result"])
assert(audit["self_test_policy"] == "bounded_current_vm_cleanup_diagnostic")
assert(audit["missing_capability_keys"].size() == 0)
assert(audit["missing_contract_keys"].size() == 0)
audit["problems"].push("mutated")
assert(p2ipc.audit()["problems"].size() == 0)
var audit_problems = p2ipc.audit_problems()
assert(audit_problems.size() == 0)
audit_problems.push("mutated")
assert(p2ipc.audit_problems().size() == 0)
assert(p2ipc.audit_ok())
var cross_cog_policy = p2ipc.cross_cog_channel_policy()
assert(cross_cog_policy["ok"])
assert(!cross_cog_policy["supported"])
assert(cross_cog_policy["capability"] == "cross_cog_channel")
assert(cross_cog_policy["policy"] == "unsupported_no_cross_cog_wakeup_or_serialization")
assert(cross_cog_policy["current_vm_channel"])
assert(!cross_cog_policy["cross_vm"])
assert(!cross_cog_policy["cross_cog_wakeup"])
assert(!cross_cog_policy["serialization"])
assert(!cross_cog_policy["ownership_transfer"])
assert(cross_cog_policy["safe_helpers"].find("p2.channel.new") >= 0)
assert(cross_cog_policy["unsupported_helpers"].find("p2ipc.cross_cog_channel") >= 0)
cross_cog_policy["safe_helpers"].push("mutated")
assert(p2ipc.cross_cog_channel_policy()["safe_helpers"].find("mutated") == nil)
expect_error(def () p2ipc.cross_cog_channel(1) end)
expect_error(def () p2ipc.cross_cog_channel("bad") end)
expect_error(def () p2ipc.cross_cog_channel(0) end)
var attention = p2ipc.attention_policy()
assert(attention["policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(!attention["bounded_attention_wait"])
assert(attention["wait_helper"] == "p2.cog.wait_attention_result")
assert(!attention["cross_cog_wakeup"])
assert(!attention["channel_wakeup"])
assert(!attention["mailbox_wakeup"])
assert(attention["current_vm_only"])
assert(type(p2ipc.attention_policy_value) == "function")
assert(p2ipc.attention_policy_value("policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.attention_policy_value("bounded_attention_wait") == false)
assert(p2ipc.attention_policy_value("cross_cog_wakeup") == false)
assert(p2ipc.attention_policy_value("channel_wakeup") == false)
assert(p2ipc.attention_policy_value("mailbox_wakeup") == false)
assert(p2ipc.attention_policy_value("current_vm_only"))
assert(p2ipc.attention_policy_value("missing") == nil)
assert(p2ipc.attention_policy_value(nil) == nil)
attention["bounded_attention_wait"] = true
assert(!p2ipc.attention_policy()["bounded_attention_wait"])

var payload = p2ipc.payload_result("abc")
assert(payload["ok"])
assert(payload["present"])
assert(payload["value"] == "abc")
assert(payload["payload_contract"])
assert(payload["current_vm_reference"])
assert(!payload["serialized"])
assert(!payload["ownership_transfer"])
assert(payload["payload_type"] == "string")
assert(!payload["copyable_policy_available"])
assert(!payload["cross_vm_copyable"])
assert(payload["copyable_kind"] == nil)
assert(payload["copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
var payload_list_value = [1, 2]
var payload_list = p2ipc.payload_result(payload_list_value)
assert(payload_list["value"] == payload_list_value)
assert(payload_list["payload_type"] == "instance")
assert(isinstance(payload_list["value"], list))
assert(!payload_list["copyable_policy_available"])
var self_test = p2ipc.self_test_result(3)
assert(self_test["ok"])
assert(self_test["iterations"] == 3)
assert(self_test["checks"] > 0)
assert(self_test["failure_count"] == 0)
assert(self_test["failures"].size() == 0)
assert(self_test["policy"] == "bounded_current_vm_cleanup_diagnostic")
self_test["failures"].push("mutated")
assert(p2ipc.self_test_result(0)["failures"].size() == 0)
var invalid_self_test = p2ipc.self_test_result("bad")
assert(!invalid_self_test["ok"])
assert(invalid_self_test["error"] == "invalid_iterations")

var ch = p2.channel.new(2)
var ch_info = ch.info()
assert(ch_info["kind"] == "Channel")
assert(ch._task_kind == "p2ipc_channel")
assert(ch_info["depth"] == 2)
assert(ch_info["size"] == 0)
assert(ch_info["free"] == 2)
assert(ch_info["hardware_lock"])
assert(ch_info["lock_id"] >= 0)
var ch_life = ch.lifecycle_result()
assert(ch_life["ok"])
assert(ch_life["kind"] == "Channel")
assert(ch_life["task_kind"] == "p2ipc_channel")
assert(ch_life["usable"])
assert(!ch_life["closed"])
assert(ch_life["pending_payloads"] == 0)
assert(ch_life["holds_lock_resource"])
assert(ch_life["lock_id"] == ch_info["lock_id"])
assert(ch_life["cleanup_policy"] == "clear_or_close_releases_payloads_and_close_releases_lock")
assert(ch_life["current_vm"])
assert(!ch_life["cross_vm"])
assert(!ch_life["serialized"])
assert(!ch_life["ownership_transfer"])
assert(ch_life["ownership_policy"] == "caller_keeps_current_vm_object_ownership")
assert(p2ipc.lifecycle_result(ch)["kind"] == "Channel")
var bad_life = p2ipc.lifecycle_result(nil)
assert(!bad_life["ok"])
assert(bad_life["error"] == "invalid_object")
ch_info["size"] = 99
assert(ch.info()["size"] == 0)
var ch_ready_empty = ch.ready_result()
assert(ch_ready_empty["ok"])
assert(!ch_ready_empty["ready"])
assert(ch_ready_empty["mode"] == "recv")
assert(!ch_ready_empty["can_recv"])
assert(ch_ready_empty["can_send"])
assert(ch_ready_empty["size"] == 0)
assert(ch_ready_empty["free"] == 2)
assert(!ch_ready_empty["closed"])
var ch_ready_send_empty = ch.ready_result("send")
assert(ch_ready_send_empty["ok"])
assert(ch_ready_send_empty["ready"])
assert(ch_ready_send_empty["mode"] == "send")
var ch_ready_put_empty = ch.ready_result("put")
assert(ch_ready_put_empty["ok"])
assert(ch_ready_put_empty["ready"])
assert(ch_ready_put_empty["mode"] == "send")
assert(ch.send("a"))
assert(ch.send("b"))
assert(!ch.send("c"))
assert(ch.size() == 2)
assert(ch.free() == 0)
var ch_ready_full_recv = ch.ready_result("recv")
assert(ch_ready_full_recv["ok"])
assert(ch_ready_full_recv["ready"])
assert(ch_ready_full_recv["can_recv"])
assert(!ch_ready_full_recv["can_send"])
var ch_ready_full_get = ch.ready_result("get")
assert(ch_ready_full_get["ok"])
assert(ch_ready_full_get["ready"])
assert(ch_ready_full_get["mode"] == "recv")
var ch_ready_full_send = ch.ready_result("send")
assert(ch_ready_full_send["ok"])
assert(!ch_ready_full_send["ready"])
assert(!ch_ready_full_send["can_send"])
var ch_bad_ready = ch.ready_result("bad")
assert(!ch_bad_ready["ok"])
assert(ch_bad_ready["error"] == "invalid_mode")
assert(ch.info()["size"] == 2)
assert(ch.info()["free"] == 0)
assert(ch.recv() == "a")
assert(ch.recv() == "b")
assert(ch.recv() == nil)
var ch_nil_send = ch.send_result(nil)
assert(ch_nil_send["ok"])
assert(ch_nil_send["sent"])
assert(ch_nil_send["size"] == 1)
assert(ch_nil_send["free"] == 1)
assert(ch_nil_send["payload_contract"])
assert(ch_nil_send["current_vm_reference"])
assert(!ch_nil_send["serialized"])
assert(!ch_nil_send["ownership_transfer"])
assert(ch_nil_send["payload_type"] == "nil")
assert(ch_nil_send["serialization_policy"] == "unsupported_current_vm_references_only")
assert(ch_nil_send["ownership_policy"] == "caller_keeps_current_vm_object_ownership")
var ch_nil_recv = ch.recv_result()
assert(ch_nil_recv["ok"])
assert(ch_nil_recv["found"])
assert(ch_nil_recv["value"] == nil)
assert(ch_nil_recv["size"] == 0)
assert(ch_nil_recv["free"] == 2)
assert(ch_nil_recv["payload_contract"])
assert(ch_nil_recv["current_vm_reference"])
assert(ch_nil_recv["payload_type"] == "nil")
var ch_empty_recv = ch.recv_result()
assert(ch_empty_recv["ok"])
assert(!ch_empty_recv["found"])
assert(ch_empty_recv["value"] == nil)
assert(ch_empty_recv["payload_contract"])
assert(!ch_empty_recv["current_vm_reference"])
assert(ch_empty_recv["payload_type"] == nil)
assert(ch.send_result("x")["ok"])
assert(ch.send_result("y")["ok"])
var ch_full_send = ch.send_result("z")
assert(!ch_full_send["ok"])
assert(!ch_full_send["sent"])
assert(ch_full_send["error"] == "full")
assert(ch_full_send["size"] == 2)
var ch_snapshot = ch.snapshot_result()
assert(ch_snapshot["ok"])
assert(ch_snapshot["size"] == 2)
assert(ch_snapshot["free"] == 0)
assert(ch_snapshot["depth"] == 2)
assert(ch_snapshot["items"].size() == 2)
assert(ch_snapshot["items"][0] == "x")
assert(ch_snapshot["items"][1] == "y")
assert(ch_snapshot["payload_contract"])
assert(ch_snapshot["current_vm_reference"])
assert(!ch_snapshot["serialized"])
assert(!ch_snapshot["ownership_transfer"])
ch_snapshot["items"].clear()
assert(ch.size() == 2)
assert(ch.recv() == "x")
assert(ch.recv() == "y")
var ch_empty_snapshot = ch.snapshot_result()
assert(ch_empty_snapshot["ok"])
assert(ch_empty_snapshot["items"].size() == 0)
assert(!ch_empty_snapshot["current_vm_reference"])
assert(ch.send("keep"))
assert(ch.send(nil))
ch_life = ch.lifecycle_result()
assert(ch_life["pending_payloads"] == 2)
assert(ch_life["size"] == 2)
var ch_clear = ch.clear_result()
assert(ch_clear["ok"])
assert(ch_clear["cleared"])
assert(ch_clear["released_payloads"] == 2)
assert(ch_clear["size"] == 0)
assert(ch_clear["free"] == 2)
assert(ch.size() == 0)
assert(ch.free() == 2)
assert(ch.recv() == nil)
assert(ch.send("reuse"))
assert(ch.recv() == "reuse")
var ch_clear_empty = ch.clear_result()
assert(ch_clear_empty["ok"])
assert(ch_clear_empty["released_payloads"] == 0)
var ch_close = ch.close_result()
assert(ch_close["ok"])
assert(ch_close["closed"])
assert(!ch_close["was_closed"])
assert(ch_close["depth"] == 2)
assert(ch_close["size"] == 0)
assert(ch_close["free"] == 2)
assert(ch_close["previous_size"] == 0)
assert(ch_close["previous_free"] == 2)
assert(ch_close["released_payloads"] == 0)
assert(ch_close["hardware_lock"])
assert(ch_close["lock_id"] == ch_info["lock_id"])
assert(ch.info()["closed"])
assert(ch.info()["lock_id"] == -1)
ch_life = ch.lifecycle_result()
assert(ch_life["ok"])
assert(ch_life["closed"])
assert(!ch_life["usable"])
assert(!ch_life["holds_lock_resource"])
assert(ch_life["lock_id"] == -1)
assert(!ch.send("after-close"))
assert(ch.recv() == nil)
var ch_closed_send = ch.send_result("after-close")
assert(!ch_closed_send["ok"])
assert(!ch_closed_send["sent"])
assert(ch_closed_send["error"] == "closed")
var ch_closed_recv = ch.recv_result()
assert(!ch_closed_recv["ok"])
assert(!ch_closed_recv["found"])
assert(ch_closed_recv["error"] == "closed")
var ch_closed_snapshot = ch.snapshot_result()
assert(!ch_closed_snapshot["ok"])
assert(ch_closed_snapshot["error"] == "closed")
assert(ch_closed_snapshot["items"].size() == 0)
var ch_closed_ready = ch.ready_result("recv")
assert(!ch_closed_ready["ok"])
assert(!ch_closed_ready["ready"])
assert(ch_closed_ready["error"] == "closed")
assert(ch_closed_ready["closed"])
assert(!ch.clear())
var ch_closed_clear = ch.clear_result()
assert(!ch_closed_clear["ok"])
assert(!ch_closed_clear["cleared"])
assert(ch_closed_clear["error"] == "closed")
var ch_close_again = ch.close_result()
assert(ch_close_again["ok"])
assert(ch_close_again["was_closed"])
assert(ch_close_again["lock_id"] == -1)
assert(!ch_close_again["hardware_lock"])

var ch_close_full = p2.channel.new(3)
assert(ch_close_full.send("left"))
assert(ch_close_full.send(nil))
var ch_close_full_report = ch_close_full.close_result()
assert(ch_close_full_report["ok"])
assert(ch_close_full_report["previous_size"] == 2)
assert(ch_close_full_report["released_payloads"] == 2)
assert(ch_close_full_report["size"] == 0)
assert(ch_close_full_report["free"] == 3)
assert(ch_close_full.size() == 0)
assert(ch_close_full.free() == 3)
assert(ch_close_full.recv() == nil)

var default_ch = p2.channel.new()
for i : 0..7
    assert(default_ch.send(i))
end
assert(default_ch.size() == 8)
assert(default_ch.free() == 0)
assert(!default_ch.send(8))
assert(default_ch.recv() == 0)
assert(default_ch.free() == 1)
assert(default_ch.close())

var zero_ch = p2.channel.new(0)
assert(zero_ch.size() == 0)
assert(zero_ch.free() == 0)
assert(!zero_ch.send("x"))
assert(zero_ch.recv() == nil)
assert(zero_ch.close())

var invalid_ch = p2.channel.new("bad")
assert(invalid_ch.size() == 0)
assert(invalid_ch.free() == 0)
assert(!invalid_ch.send("x"))
assert(invalid_ch.close())

var negative_ch = p2.channel.new(-2)
assert(negative_ch.size() == 0)
assert(negative_ch.free() == 0)
assert(!negative_ch.send("x"))
assert(negative_ch.close())

var mb = p2.mailbox.new()
assert(mb._task_kind == "p2ipc_mailbox")
var mb_info = mb.info()
assert(mb_info["kind"] == "Mailbox")
assert(!mb_info["ready"])
assert(mb_info["hardware_lock"])
var mb_life = mb.lifecycle_result()
assert(mb_life["ok"])
assert(mb_life["kind"] == "Mailbox")
assert(mb_life["task_kind"] == "p2ipc_mailbox")
assert(mb_life["usable"])
assert(!mb_life["closed"])
assert(mb_life["pending_payloads"] == 0)
assert(mb_life["holds_lock_resource"])
assert(mb_life["cleanup_policy"] == "clear_or_close_releases_payload_and_close_releases_lock")
mb_info["ready"] = true
assert(!mb.info()["ready"])
assert(!mb.ready())
var mb_ready_empty = mb.ready_result()
assert(mb_ready_empty["ok"])
assert(!mb_ready_empty["ready"])
assert(mb_ready_empty["mode"] == "get")
assert(!mb_ready_empty["can_get"])
assert(mb_ready_empty["can_put"])
assert(!mb_ready_empty["closed"])
var mb_ready_put_empty = mb.ready_result("put")
assert(mb_ready_put_empty["ok"])
assert(mb_ready_put_empty["ready"])
assert(mb_ready_put_empty["mode"] == "put")
var mb_ready_send_empty = mb.ready_result("send")
assert(mb_ready_send_empty["ok"])
assert(mb_ready_send_empty["ready"])
assert(mb_ready_send_empty["mode"] == "put")
assert(mb.put(42))
assert(mb.ready())
assert(mb.info()["ready"])
mb_life = mb.lifecycle_result()
assert(mb_life["ready"])
assert(mb_life["pending_payloads"] == 1)
var mb_ready_full_get = mb.ready_result("get")
assert(mb_ready_full_get["ok"])
assert(mb_ready_full_get["ready"])
assert(mb_ready_full_get["can_get"])
assert(!mb_ready_full_get["can_put"])
var mb_ready_full_recv = mb.ready_result("recv")
assert(mb_ready_full_recv["ok"])
assert(mb_ready_full_recv["ready"])
assert(mb_ready_full_recv["mode"] == "get")
var mb_ready_full_put = mb.ready_result("put")
assert(mb_ready_full_put["ok"])
assert(!mb_ready_full_put["ready"])
assert(!mb_ready_full_put["can_put"])
var mb_bad_ready = mb.ready_result("bad")
assert(!mb_bad_ready["ok"])
assert(mb_bad_ready["error"] == "invalid_mode")
assert(!mb.put(43))
assert(mb.get() == 42)
assert(mb.get() == nil)
var mb_nil_put = mb.put_result(nil)
assert(mb_nil_put["ok"])
assert(mb_nil_put["stored"])
assert(mb_nil_put["ready"])
assert(mb_nil_put["payload_contract"])
assert(mb_nil_put["current_vm_reference"])
assert(!mb_nil_put["serialized"])
assert(!mb_nil_put["ownership_transfer"])
assert(mb_nil_put["payload_type"] == "nil")
var mb_full_put = mb.put_result(99)
assert(!mb_full_put["ok"])
assert(!mb_full_put["stored"])
assert(mb_full_put["error"] == "full")
assert(mb_full_put["payload_contract"])
assert(mb_full_put["current_vm_reference"])
assert(mb_full_put["payload_type"] == "int")
var mb_peek_nil = mb.peek_result()
assert(mb_peek_nil["ok"])
assert(mb_peek_nil["found"])
assert(mb_peek_nil["value"] == nil)
assert(mb_peek_nil["ready"])
assert(mb_peek_nil["payload_contract"])
assert(mb_peek_nil["current_vm_reference"])
assert(mb_peek_nil["payload_type"] == "nil")
assert(mb.ready())
var mb_nil_get = mb.get_result()
assert(mb_nil_get["ok"])
assert(mb_nil_get["found"])
assert(mb_nil_get["value"] == nil)
assert(!mb_nil_get["ready"])
assert(mb_nil_get["payload_contract"])
assert(mb_nil_get["current_vm_reference"])
assert(mb_nil_get["payload_type"] == "nil")
var mb_empty_get = mb.get_result()
assert(mb_empty_get["ok"])
assert(!mb_empty_get["found"])
assert(mb_empty_get["value"] == nil)
assert(mb.put("keep"))
var mb_peek = mb.peek_result()
assert(mb_peek["ok"])
assert(mb_peek["found"])
assert(mb_peek["value"] == "keep")
assert(mb.ready())
var mb_clear = mb.clear_result()
assert(mb_clear["ok"])
assert(mb_clear["cleared"])
assert(mb_clear["released_payload"])
assert(!mb_clear["ready"])
assert(!mb.ready())
assert(mb.get() == nil)
assert(mb.put("reuse"))
assert(mb.get() == "reuse")
var mb_clear_empty = mb.clear_result()
assert(mb_clear_empty["ok"])
assert(!mb_clear_empty["released_payload"])
var mb_close = mb.close_result()
assert(mb_close["ok"])
assert(mb_close["closed"])
assert(!mb_close["was_closed"])
assert(!mb_close["ready"])
assert(!mb_close["previous_ready"])
assert(!mb_close["released_payload"])
assert(mb_close["hardware_lock"])
assert(mb.info()["closed"])
mb_life = mb.lifecycle_result()
assert(mb_life["closed"])
assert(!mb_life["usable"])
assert(!mb_life["holds_lock_resource"])
var mb_closed_ready = mb.ready_result("get")
assert(!mb_closed_ready["ok"])
assert(!mb_closed_ready["ready"])
assert(mb_closed_ready["error"] == "closed")
assert(mb_closed_ready["closed"])
assert(mb.info()["lock_id"] == -1)
assert(!mb.put("after-close"))
assert(mb.get() == nil)
var mb_closed_put = mb.put_result("after-close")
assert(!mb_closed_put["ok"])
assert(!mb_closed_put["stored"])
assert(mb_closed_put["error"] == "closed")
var mb_closed_get = mb.get_result()
assert(!mb_closed_get["ok"])
assert(!mb_closed_get["found"])
assert(mb_closed_get["error"] == "closed")
var mb_closed_peek = mb.peek_result()
assert(!mb_closed_peek["ok"])
assert(!mb_closed_peek["found"])
assert(mb_closed_peek["error"] == "closed")
assert(!mb.clear())
var mb_closed_clear = mb.clear_result()
assert(!mb_closed_clear["ok"])
assert(!mb_closed_clear["cleared"])
assert(mb_closed_clear["error"] == "closed")
var mb_close_again = mb.close_result()
assert(mb_close_again["ok"])
assert(mb_close_again["was_closed"])
assert(mb_close_again["lock_id"] == -1)
assert(!mb_close_again["hardware_lock"])

var mb_close_full = p2.mailbox.new()
assert(mb_close_full.put("held"))
var mb_close_full_report = mb_close_full.close_result()
assert(mb_close_full_report["ok"])
assert(mb_close_full_report["previous_ready"])
assert(mb_close_full_report["released_payload"])
assert(!mb_close_full_report["ready"])
assert(!mb_close_full.ready())
assert(mb_close_full.get() == nil)

var buf = p2.shared.Buffer(4)
var buf_info = buf.info()
assert(buf_info["kind"] == "Buffer")
assert(buf_info["size"] == 4)
var buf_life = buf.lifecycle_result()
assert(buf_life["ok"])
assert(buf_life["kind"] == "Buffer")
assert(buf_life["usable"])
assert(!buf_life["closed"])
assert(buf_life["size"] == 4)
assert(!buf_life["hardware_lock"])
assert(!buf_life["holds_lock_resource"])
assert(buf_life["cleanup_policy"] == "clear_zeroes_bytes")
buf_info["size"] = 99
assert(buf.info()["size"] == 4)
assert(buf.size() == 4)
assert(buf.aslist() == [0, 0, 0, 0])
assert(buf.write(0, 17))
assert(buf.write(3, 255))
assert(!buf.write(4, 1))
assert(!buf.write(1, 256))
assert(buf.read(0) == 17)
assert(buf.read(3) == 255)
assert(buf.read(4) == nil)
assert(buf.fill(7))
assert(buf.aslist() == [7, 7, 7, 7])
var snap = buf.aslist()
snap[0] = 99
assert(buf.read(0) == 7)
assert(!buf.write(-1, 1))
assert(!buf.write(0, -1))
assert(!buf.write(nil, 1))
assert(!buf.write("bad", 1))
assert(!buf.write(0, nil))
assert(!buf.write(0, "bad"))
assert(!buf.fill(256))
assert(!buf.fill(nil))
assert(!buf.fill("bad"))
assert(buf.aslist() == [7, 7, 7, 7])
var buf_write = buf.write_result(1, 33)
assert(buf_write["ok"])
assert(buf_write["written"])
var buf_read = buf.read_result(1)
assert(buf_read["ok"])
assert(buf_read["found"])
assert(buf_read["value"] == 33)
var buf_bad_offset = buf.read_result("bad")
assert(!buf_bad_offset["ok"])
assert(buf_bad_offset["error"] == "invalid_offset")
var buf_oob = buf.write_result(4, 1)
assert(!buf_oob["ok"])
assert(buf_oob["error"] == "offset_out_of_range")
var buf_bad_value = buf.write_result(0, 256)
assert(!buf_bad_value["ok"])
assert(buf_bad_value["error"] == "value_out_of_range")
var buf_bad_type = buf.fill_result(nil)
assert(!buf_bad_type["ok"])
assert(buf_bad_type["error"] == "invalid_value")
var buf_fill = buf.fill_result(5)
assert(buf_fill["ok"])
assert(buf_fill["filled"])
assert(buf.aslist() == [5, 5, 5, 5])
assert(buf.clear())
assert(buf.aslist() == [0, 0, 0, 0])
assert(buf.fill(9))
var buf_clear = buf.clear_result()
assert(buf_clear["ok"])
assert(buf_clear["cleared"])
assert(buf_clear["size"] == 4)
assert(buf_clear["released_bytes"] == 4)
assert(buf.aslist() == [0, 0, 0, 0])

var empty_buf = p2.shared.Buffer(-3)
assert(empty_buf.size() == 0)
assert(empty_buf.read(0) == nil)
assert(!empty_buf.write(0, 1))
assert(empty_buf.aslist() == [])
var empty_buf_clear = empty_buf.clear_result()
assert(empty_buf_clear["ok"])
assert(empty_buf_clear["size"] == 0)
assert(empty_buf_clear["released_bytes"] == 0)

var invalid_buf = p2.shared.Buffer("bad")
assert(invalid_buf.size() == 0)
assert(invalid_buf.aslist() == [])

var m = p2.mutex.new()
assert(m.id() >= 0)
var m_info = m.info()
assert(m_info["kind"] == "Mutex")
assert(m_info["hardware"])
assert(m_info["lock_id"] == m.id())
var m_life = m.lifecycle_result()
assert(m_life["ok"])
assert(m_life["kind"] == "Mutex")
assert(m_life["usable"])
assert(!m_life["closed"])
assert(m_life["holds_lock_resource"])
assert(m_life["cleanup_policy"] == "close_releases_hardware_lock")
var m_unlock_unlocked = m.unlock_result()
assert(!m_unlock_unlocked["ok"])
assert(!m_unlock_unlocked["unlocked"])
assert(m_unlock_unlocked["error"] == "not_locked")
var m_lock_result = m.lock_result()
assert(m_lock_result["ok"])
assert(m_lock_result["locked"])
assert(m_lock_result["hardware"])
var m_lock_busy = m.lock_result()
assert(!m_lock_busy["ok"])
assert(!m_lock_busy["locked"])
assert(m_lock_busy["error"] == "busy")
var m_unlock_result = m.unlock_result()
assert(m_unlock_result["ok"])
assert(m_unlock_result["unlocked"])
assert(m.lock())
assert(!m.lock())
assert(m.unlock())
var m_close_result = m.close_result()
assert(m_close_result["ok"])
assert(m_close_result["closed"])
assert(!m_close_result["was_closed"])
assert(m_close_result["hardware"])
assert(m_close_result["lock_id"] == m_info["lock_id"])
assert(m.info()["closed"])
assert(m.id() == -1)
m_life = m.lifecycle_result()
assert(m_life["closed"])
assert(!m_life["usable"])
assert(!m_life["holds_lock_resource"])
assert(!m.lock())
assert(!m.unlock())
var m_closed_lock = m.lock_result()
assert(!m_closed_lock["ok"])
assert(m_closed_lock["error"] == "closed")
var m_closed_unlock = m.unlock_result()
assert(!m_closed_unlock["ok"])
assert(m_closed_unlock["error"] == "closed")
var m_closed_again = m.close_result()
assert(m_closed_again["ok"])
assert(m_closed_again["closed"])
assert(m_closed_again["was_closed"])
assert(m.close())

var blocked_ch = p2.channel.new(1)
assert(blocked_ch.mutex.lock())
assert(!blocked_ch.send("x"))
assert(!blocked_ch.clear())
var blocked_clear = blocked_ch.clear_result()
assert(!blocked_clear["ok"])
assert(!blocked_clear["cleared"])
assert(blocked_clear["error"] == "lock_busy")
var blocked_send = blocked_ch.send_result("x")
assert(!blocked_send["ok"])
assert(!blocked_send["sent"])
assert(blocked_send["error"] == "lock_busy")
assert(blocked_ch.recv() == nil)
var blocked_recv = blocked_ch.recv_result()
assert(!blocked_recv["ok"])
assert(!blocked_recv["found"])
assert(blocked_recv["error"] == "lock_busy")
assert(blocked_ch.mutex.unlock())
assert(blocked_ch.send("x"))
assert(blocked_ch.recv() == "x")
assert(blocked_ch.close())

var blocked_mb = p2.mailbox.new()
assert(blocked_mb.mutex.lock())
assert(!blocked_mb.put("x"))
assert(!blocked_mb.clear())
var blocked_mb_clear = blocked_mb.clear_result()
assert(!blocked_mb_clear["ok"])
assert(!blocked_mb_clear["cleared"])
assert(blocked_mb_clear["error"] == "lock_busy")
assert(blocked_mb.mutex.unlock())
assert(blocked_mb.put("x"))
assert(blocked_mb.clear())
assert(!blocked_mb.ready())
assert(blocked_mb.close())

lock.new = def()
    return -1
end
var p2ipc_alloc_fail = run_file("modules/p2ipc.be")
assert(type(p2ipc_alloc_fail) == "module")
var fallback_alloc = p2.mutex.new()
assert(fallback_alloc.id() == -1)
var fallback_alloc_info = fallback_alloc.info()
assert(fallback_alloc_info["kind"] == "Mutex")
assert(!fallback_alloc_info["hardware"])
assert(!fallback_alloc_info["locked"])
var fallback_alloc_unlocked = fallback_alloc.unlock_result()
assert(!fallback_alloc_unlocked["ok"])
assert(fallback_alloc_unlocked["error"] == "not_locked")
var fallback_alloc_lock = fallback_alloc.lock_result()
assert(fallback_alloc_lock["ok"])
assert(fallback_alloc_lock["locked"])
assert(!fallback_alloc_lock["hardware"])
var fallback_alloc_busy = fallback_alloc.lock_result()
assert(!fallback_alloc_busy["ok"])
assert(fallback_alloc_busy["error"] == "busy")
var fallback_alloc_unlock = fallback_alloc.unlock_result()
assert(fallback_alloc_unlock["ok"])
assert(fallback_alloc_unlock["unlocked"])
assert(fallback_alloc.lock())
assert(fallback_alloc.info()["locked"])
assert(!fallback_alloc.lock())
assert(fallback_alloc.unlock())
assert(!fallback_alloc.unlock())
assert(fallback_alloc.close())
assert(fallback_alloc.info()["closed"])
assert(!fallback_alloc.lock())
assert(!fallback_alloc.unlock())
assert(fallback_alloc.lock_result()["error"] == "closed")
assert(fallback_alloc.unlock_result()["error"] == "closed")
assert(fallback_alloc.close())

p2.lock = nil
var p2ipc_fallback = run_file("modules/p2ipc.be")
assert(type(p2ipc_fallback) == "module")
assert(!p2ipc_fallback.capabilities()["hardware_lock_backend_available"])
assert(p2ipc_fallback.capability("fallback_mutex"))
assert(!p2ipc_fallback.contract()["hardware_lock_backend_available"])
var fallback = p2.mutex.new()
assert(fallback.id() == -1)
var fallback_close = fallback.close_result()
assert(fallback_close["ok"])
assert(fallback_close["closed"])
assert(!fallback_close["was_closed"])
assert(!fallback_close["hardware"])
assert(fallback_close["lock_id"] == -1)
assert(fallback.lock_result()["error"] == "closed")
var fallback_recheck = fallback.close_result()
assert(fallback_recheck["was_closed"])

fallback = p2.mutex.new()
assert(fallback.lock())
assert(!fallback.lock())
assert(fallback.unlock())
assert(!fallback.unlock())
assert(fallback.close())
assert(fallback.info()["closed"])
assert(!fallback.lock())
assert(!fallback.unlock())
assert(fallback.close())

var fallback_ch = p2.channel.new(1)
var fallback_ch_info = fallback_ch.info()
assert(fallback_ch_info["kind"] == "Channel")
assert(!fallback_ch_info["hardware_lock"])
assert(fallback_ch_info["lock_id"] == -1)
assert(fallback_ch.mutex.lock())
assert(!fallback_ch.send("blocked"))
assert(fallback_ch.recv() == nil)
assert(fallback_ch.mutex.unlock())
assert(fallback_ch.send("ok"))
assert(fallback_ch.recv() == "ok")
assert(fallback_ch.close())
assert(fallback_ch.info()["closed"])
assert(!fallback_ch.send("after-close"))
assert(fallback_ch.send_result("after-close")["error"] == "closed")
