print("P2_SMOKE_BEGIN p2compat_child_vm")

import p2

def check(cond, label)
    if !cond
        print("P2_SMOKE_FAIL p2compat_child_vm", label)
    end
    assert(cond)
end

check(type(p2.vm_copyable) == "function", "vm_copyable_function")
var copy_nil = p2.vm_copyable(nil)
var copy_bool = p2.vm_copyable(true)
var copy_int = p2.vm_copyable(42)
var copy_string = p2.vm_copyable("abc")
check(copy_nil["ok"] && copy_nil["kind"] == "nil", "vm_copyable_nil")
check(copy_bool["ok"] && copy_bool["kind"] == "bool", "vm_copyable_bool")
check(copy_int["ok"] && copy_int["kind"] == "int", "vm_copyable_int")
check(copy_string["ok"] && copy_string["kind"] == "string", "vm_copyable_string")
check(copy_string["reason"] == "bounded copy", "vm_copyable_string_reason")

var reject_list = p2.vm_copyable([1])
var reject_map = p2.vm_copyable({"a": 1})
def local_probe()
    return 1
end
var reject_fn = p2.vm_copyable(local_probe)
check(!reject_list["ok"] && reject_list["kind"] == "list", "vm_copyable_list")
check(!reject_map["ok"] && reject_map["kind"] == "map", "vm_copyable_map")
check(!reject_fn["ok"] && reject_fn["kind"] == "function", "vm_copyable_function_rejected")

check(type(p2.vm_copyable_args) == "function", "vm_copyable_args_function")
var copy_args_empty = p2.vm_copyable_args()
check(copy_args_empty["ok"], "vm_copyable_args_empty_ok")
check(copy_args_empty["count"] == 0, "vm_copyable_args_empty_count")
check(copy_args_empty["copyable_count"] == 0, "vm_copyable_args_empty_copyable")
check(copy_args_empty["rejected_count"] == 0, "vm_copyable_args_empty_rejected")
check(copy_args_empty["first_rejected_index"] == -1, "vm_copyable_args_empty_first")

var copy_args_ok = p2.vm_copyable_args(nil, true, 7, "abc")
check(copy_args_ok["ok"], "vm_copyable_args_ok")
check(copy_args_ok["count"] == 4, "vm_copyable_args_ok_count")
check(copy_args_ok["copyable_count"] == 4, "vm_copyable_args_ok_copyable")
check(copy_args_ok["rejected_count"] == 0, "vm_copyable_args_ok_rejected")
check(copy_args_ok["policy"] == "primitive_copy_only", "vm_copyable_args_policy")
check(copy_args_ok["bounded_string_copy"], "vm_copyable_args_bounded_string")
check(!copy_args_ok["ownership_transfer"], "vm_copyable_args_no_ownership")
check(!copy_args_ok["shared_mutable_state"], "vm_copyable_args_no_shared_state")
check(!copy_args_ok["resource_transfer"], "vm_copyable_args_no_resource")

var copy_args_reject = p2.vm_copyable_args(1, [2], {"a": 3})
check(!copy_args_reject["ok"], "vm_copyable_args_reject_ok")
check(copy_args_reject["count"] == 3, "vm_copyable_args_reject_count")
check(copy_args_reject["copyable_count"] == 1, "vm_copyable_args_reject_copyable")
check(copy_args_reject["rejected_count"] == 2, "vm_copyable_args_reject_rejected")
check(copy_args_reject["first_rejected_index"] == 2, "vm_copyable_args_reject_first")
check(copy_args_reject["first_rejected_kind"] == "list", "vm_copyable_args_reject_kind")

var heap = p2.heap_info()
var heap_bytes = heap["vm_partition_bytes"]
check(type(heap_bytes) == "int", "vm_partition_bytes_type")
check(heap_bytes > 0, "vm_partition_bytes_positive")
check(heap["vm_partition_max"] >= 2, "vm_partition_max")
check(heap["vm_partition_capacity"] >= 1, "vm_partition_capacity")
check(heap["vm_partition_free_capacity"] >= 0, "vm_partition_free_capacity")
check(heap["vm_partition_free_capacity"] <= heap["vm_partition_capacity"], "vm_partition_free_capacity_bounds")
check(heap["vm_partition_created"] >= 0, "vm_partition_created")
check(heap["vm_partition_current"] == -1, "vm_partition_current_parent")

var child_arg_reject = p2.vm_call(0, heap_bytes, "def bad(a,b) return 1 end", "bad", 1, [1])
check(!child_arg_reject["ok"], "vm_call_bad_args_not_ok")
check(child_arg_reject["status"] == "args_rejected", "vm_call_bad_args_status")
check(!child_arg_reject["args_copyable"], "vm_call_bad_args_copyable")
check(child_arg_reject["arg_rejected_count"] == 1, "vm_call_bad_args_rejected_count")
check(child_arg_reject["first_arg_rejected_index"] == 2, "vm_call_bad_args_first")
check(child_arg_reject["first_arg_rejected_kind"] == "list", "vm_call_bad_args_kind")
check(!child_arg_reject["partition_ready"], "vm_call_bad_args_no_partition")
check(!child_arg_reject["child_created"], "vm_call_bad_args_no_child")
check(!child_arg_reject["runtime_locked"], "vm_call_bad_args_no_lock")

var child_call_ok = p2.vm_call_once(0, heap_bytes, "def five() return 5 end", "five")
check(child_call_ok["ok"], "vm_call_once_ok")
check(child_call_ok["status"] == "ok", "vm_call_once_status")
check(child_call_ok["args_copyable"], "vm_call_once_args_copyable")
check(child_call_ok["call_result"] == 0, "vm_call_once_call_result")
check(child_call_ok["result_type"] == 1, "vm_call_once_result_type")
check(child_call_ok["result_int"] == 5, "vm_call_once_result_int")
check(child_call_ok["release_attempted"], "vm_call_once_release_attempted")
check(child_call_ok["released"], "vm_call_once_released")

var child_invoke_reject = p2.vm_invoke(0, "bad", {"a": 1})
check(!child_invoke_reject["ok"], "vm_invoke_bad_args_not_ok")
check(child_invoke_reject["status"] == "args_rejected", "vm_invoke_bad_args_status")
check(!child_invoke_reject["args_copyable"], "vm_invoke_bad_args_copyable")
check(child_invoke_reject["arg_rejected_count"] == 1, "vm_invoke_bad_args_rejected_count")
check(child_invoke_reject["first_arg_rejected_index"] == 1, "vm_invoke_bad_args_first")
check(child_invoke_reject["first_arg_rejected_kind"] == "map", "vm_invoke_bad_args_kind")
check(!child_invoke_reject["selected"], "vm_invoke_bad_args_not_selected")
check(!child_invoke_reject["runtime_locked"], "vm_invoke_bad_args_no_lock")

var child_info_before = p2.vm_info(1)
check(child_info_before["ok"], "vm_info_before_ok")
check(child_info_before["status"] == "inactive", "vm_info_before_status")
check(!child_info_before["active"], "vm_info_before_inactive")
check(!child_info_before["has_child"], "vm_info_before_no_child")

var child_open = p2.vm_open(1, heap_bytes)
check(child_open["ok"], "vm_open_ok")
check(child_open["status"] == "ok" || child_open["status"] == "already_active", "vm_open_status")
check(child_open["active"], "vm_open_active")

var child_info_open = p2.vm_info(1)
check(child_info_open["ok"], "vm_info_open_ok")
check(child_info_open["status"] == "active", "vm_info_open_status")
check(child_info_open["active"], "vm_info_open_active")
check(child_info_open["has_child"], "vm_info_open_has_child")
check(child_info_open["partition_ready"], "vm_info_open_partition")

var child_eval = p2.vm_eval(1, "child_status_value=41")
check(child_eval["ok"], "vm_eval_ok")
check(child_eval["status"] == "ok", "vm_eval_status")
check(child_eval["run_result"] == 0, "vm_eval_run_result")

var child_get = p2.vm_get(1, "child_status_value")
check(child_get["ok"], "vm_get_ok")
check(child_get["status"] == "ok", "vm_get_status")
check(child_get["found"], "vm_get_found")
check(child_get["result_type"] == 1, "vm_get_result_type")
check(child_get["result_int"] == 41, "vm_get_result_int")

var child_get_missing = p2.vm_get(1, "child_status_missing")
check(!child_get_missing["ok"], "vm_get_missing_not_ok")
check(child_get_missing["status"] == "missing", "vm_get_missing_status")
check(!child_get_missing["found"], "vm_get_missing_found")

var child_close = p2.vm_close(1)
check(child_close["ok"], "vm_close_ok")
check(child_close["status"] == "ok", "vm_close_status")
check(child_close["child_deleted"], "vm_close_child_deleted")
check(child_close["released"], "vm_close_released")
check(!child_close["active"], "vm_close_inactive")

var child_info_closed = p2.vm_info(1)
check(child_info_closed["ok"], "vm_info_closed_ok")
check(child_info_closed["status"] == "inactive", "vm_info_closed_status")
check(!child_info_closed["active"], "vm_info_closed_inactive")
check(!child_info_closed["partition_ready"], "vm_info_closed_partition")

var child_eval_closed = p2.vm_eval(1, "child_status_value=99")
check(!child_eval_closed["ok"], "vm_eval_closed_not_ok")
check(child_eval_closed["status"] == "inactive", "vm_eval_closed_status")

print("P2_SMOKE_PASS p2compat_child_vm")
