print("P2_SMOKE_BEGIN string")

import string

assert(type(string) == "module")

assert(type(string.find) == "function")
assert(type(string.count) == "function")
assert(type(string.split) == "function")
assert(type(string.escape) == "function")
assert(type(string.tr) == "function")
assert(type(string.replace) == "function")
assert(type(string.format) == "function")
assert(type(string.startswith) == "function")
assert(type(string.endswith) == "function")

assert(string.find("012345", "23") == 2)
assert(string.find("012345", "23", 1) == 2)
assert(string.find("012345", "23", 1, 3) == -1)
assert(string.find("012345", "23", 2, 4) == 2)
assert(string.find("012345", "23", 3) == -1)
assert(string.find("012345", "") == 0)
assert(string.find("012345", "", 6) == 6)
assert(string.find("012345", "", 7) == -1)
assert(string.find("", "") == 0)
assert(string.find("", "", 1) == -1)

assert(string.count("012345", "") == 7)
assert(string.count("", "") == 1)
assert(string.count("012345", "", 2) == 5)
assert(string.count("abcdef", "z") == 0)
assert(string.count("121314", "1") == 3)
assert(string.count("121314", "1", 1) == 2)
assert(string.count("121314", "1", 1, 3) == 1)
assert(string.count("aaaa", "aa") == 2)

assert(string.split("a b c d e f", "1") == ["a b c d e f"])
assert(string.split("a b c d e f", " ") == ["a", "b", "c", "d", "e", "f"])
assert(string.split("a b c d e f", " ", 2) == ["a", "b", "c d e f"])
assert(string.split("a b c d e f", "") == ["a b c d e f"])

assert(string.escape("A") == '"A"')
assert(string.escape("A", true) == "'A'")
assert(string.escape("\"") == '"\\""')
assert(string.escape("\"", true) == '\'"\'')

assert(string.tr("azer", "abcde", "ABCDE") == "AzEr")
assert(string.tr("azer", "", "") == "azer")
assert(string.tr("azer", "aaa", "ABC") == "Azer")
assert(string.tr("A_b", "_", " ") == "A b")
assert(string.tr("qwerty", "qwe", "_") == "_rty")

assert(string.replace("hello", "ll", "xx") == "hexxo")
assert(string.replace("hellollo", "ll", "xx") == "hexxoxxo")
assert(string.replace("hellollo", "aa", "xx") == "hellollo")
assert(string.replace("hello", "ll", "") == "heo")
assert(string.replace("hello", "", "xx") == "hello")
assert(string.replace("hello", "", "") == "hello")
assert(string.replace("aaaa", "aa", "b") == "bb")
assert(string.replace("aaaa", "aa", "bbb") == "bbbbbb")

assert(string.format("%%") == "%")
assert(string.format("%i%%", 12) == "12%")
assert(string.format("%i%%%i", 12, 13) == "12%13")
assert(string.format("%s%%", "foo") == "foo%")
assert(string.format("%.1f%%", 3.5) == "3.5%")
assert(string.format("%i", "03") == "3")
assert(string.format("%i", nil) == "")
assert(string.format("%i", true) == "1")
assert(string.format("%i", false) == "0")
assert(string.format("%f", 3) == "3.000000")
assert(string.format("%.1f", 3) == "3.0")
assert(string.format("%s", nil) == "nil")
assert(string.format("%s", true) == "true")
assert(format == string.format)
assert(format("%.1f", 3) == "3.0")

var s = "azertyuiop"
assert(s[0] == "a")
assert(s[0..1] == "az")
assert(s[0..50] == s)
assert(s[-1] == "p")
assert(s[-2] == "o")
assert(s[0..-2] == "azertyuio")
assert(s[-4..-2] == "uio")
assert(s[-2..-4] == "")
assert(s[-40..-2] == "azertyuio")

assert(string.startswith("", ""))
assert(!string.startswith("", "x"))
assert(string.startswith("qwerty", "qw"))
assert(string.startswith("qwerty", "qwerty"))
assert(string.startswith("qwerty", ""))
assert(!string.startswith("qwerty", "qW"))
assert(string.startswith("qwerty", "qW", true))
assert(!string.startswith("qwerty", "qz", true))
assert(!string.startswith("qwerty", "qwertyw", true))

assert(string.endswith("", ""))
assert(!string.endswith("", "x"))
assert(string.endswith("qwerty", "ty"))
assert(string.endswith("qwerty", "qwerty"))
assert(string.endswith("qwerty", ""))
assert(!string.endswith("qwerty", "tY"))
assert(string.endswith("qwerty", "tY", true))
assert(!string.endswith("qwerty", "tr", true))
assert(!string.endswith("qwerty", "qwertyw", true))

assert("aze" * 3 == "azeazeaze")
assert("ab" * 5 == "ababababab")
assert("x" * 1 == "x")
assert("aze" * 0 == "")
assert("hello" * -1 == "")
assert("aze" * true == "aze")
assert("aze" * false == "")
assert("" * 1 == "")

print("P2_SMOKE_PASS string")
