print("P2_SMOKE_BEGIN smartpins_loopback")

import p2
import p2smart

print("P2_SMOKE_STAGE imports")

assert(p2smart.smart.normal == 0)
assert(p2smart.smart.pwm_triangle == 0x10)
assert(p2smart.smart.pwm_sawtooth == 0x12)
assert(p2smart.smart.pwm_smps == 0x14)
assert(p2smart.smart.nco_duty == 0x0e)
assert(p2smart.smart.count_rises == 0x1c)
assert(p2smart.smart.count_highs == 0x1e)
assert(p2smart.smart.adc_1x == 0x118000)
assert(p2smart.smart.adc == 0x30)
assert(p2smart.smart.dac_dither_pwm == 0x06)
assert(p2smart.smart.dac_990r_3v == 0x140000)
assert(p2smart.jumper_pair_checks().find("async_serial_drain") >= 0)

print("P2_SMOKE_STAGE constants")

def expect_error(fn)
    var caught = false
    try
        fn()
    except .. as e, m
        caught = true
    end
    assert(caught)
end

def reset_pin(pin)
    p2smart.smart.clear(pin)
    p2smart.smart.wrpin(pin, 0)
    p2smart.smart.wxpin(pin, 0)
    p2smart.smart.wypin(pin, 0)
    p2smart.smart.akpin(pin)
    p2smart.pin.float(pin)
end

def reset_pair(a, b)
    reset_pin(a)
    reset_pin(b)
end

def gpio_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.gpio_loopback_probe(out_pin, in_pin, [0, 1, 0, 1], 100)
    assert(probe["ok"])
    assert(probe["count"] == 4)
    for item : probe["results"]
        assert(item["ok"])
        assert(item["write"]["value"] == item["read"]["value"])
    end

    reset_pair(out_pin, in_pin)
    var input = p2smart.gpio_input(in_pin)
    var output = p2smart.gpio_output(out_pin, true)
    input.start()
    output.start()
    p2smart.waitus(100)
    assert(input.read_result()["value"] == 1)

    var toggled = output.toggle_result()
    p2smart.waitus(100)
    assert(toggled["value"] == 0)
    assert(input.read_result()["value"] == 0)

    output.clear()
    input.clear()
    reset_pair(out_pin, in_pin)
end

def raw_smartpin_api(pin)
    reset_pin(pin)
    var probe = p2smart.raw_smartpin_probe(pin)
    assert(probe["ok"])
    assert(type(probe["initial_read"]) == "int")
    assert(type(probe["initial_query"]) == "int")
    assert(type(probe["started_read"]) == "int")
    assert(type(probe["cleared_query"]) == "int")
    reset_pin(pin)
end

def repository_mode(pin)
    reset_pin(pin)
    var probe = p2smart.repository_probe(pin, 0x00c0ffee + pin, 0x00123400 + pin, 100)
    assert(probe["ok"])
    assert(probe["first"]["value"] == 0x00c0ffee + pin)
    assert(type(probe["first"]["raw"]) == "int")
    assert(probe["write"]["value"] == 0x00123400 + pin)
    assert(type(probe["second"]["raw"]) == "int")
    reset_pin(pin)
end

def pwm_counter_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.pwm_counter_probe(out_pin, in_pin, 200, 100, 1, 2000)
    assert(probe["ok"])
    assert(probe["pwm"]["x"] == 200 * 65536 + 1)
    assert(probe["counter"]["delta"] > 0)
    reset_pair(out_pin, in_pin)
end

def pwm_variant_counter_loopback(out_pin, in_pin, mode_name)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.pwm_variant_counter_probe(out_pin, in_pin, 200, 100, 1, mode_name, 2000)
    assert(probe["ok"])
    assert(probe["mode_name"] == mode_name)
    assert(probe["pwm"]["x"] == 200 * 65536 + 1)
    assert(probe["counter"]["delta"] > 0)
    reset_pair(out_pin, in_pin)
end

def high_counter_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.high_counter_probe(out_pin, in_pin, 1000, 100)
    assert(probe["ok"])
    assert(probe["counter"]["mode"] == p2smart.smart.count_highs)
    assert(probe["counter"]["delta"] > 0)
    reset_pair(out_pin, in_pin)
end

def counter_variant_drive_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.counter_variant_drive_probe(out_pin, in_pin, "count_highs", 1000, 100)
    assert(probe["ok"])
    assert(probe["mode_name"] == "count_highs")
    assert(probe["counter"]["mode"] == p2smart.smart.count_highs)
    assert(probe["counter"]["delta"] > 0)
    reset_pair(out_pin, in_pin)
end

def nco_counter_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.nco_counter_probe(out_pin, in_pin, 16000, 0x20000000, 2000)
    assert(probe["ok"])
    assert(probe["nco"]["increment"] == 0x20000000)
    assert(probe["counter"]["delta"] > 0)
    reset_pair(out_pin, in_pin)
end

def nco_duty_counter_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.nco_duty_counter_probe(out_pin, in_pin, 16000, 4000, 2000)
    print("P2_SMOKE_NCO_DUTY_VALUES " + str(out_pin) + "_" + str(in_pin) + " " + str(probe["ok"]) + " " + str(probe["counter"]["before"]) + " " + str(probe["counter"]["after"]) + " " + str(probe["counter"]["delta"]))
    assert(probe["nco_duty"]["bit_period"] == 16000)
    assert(probe["nco_duty"]["duty"] == 4000)
    assert(type(probe["ok"]) == "bool")
    assert(type(probe["counter"]["before"]) == "int")
    assert(type(probe["counter"]["after"]) == "int")
    assert(type(probe["counter"]["delta"]) == "int")
    reset_pair(out_pin, in_pin)
end

def pulse_counter_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.pulse_counter_probe(out_pin, in_pin, 100, 100, 8, 2000)
    assert(probe["ok"])
    assert(probe["pulse"]["count"] == 8)
    assert(probe["counter"]["delta"] > 0)
    reset_pair(out_pin, in_pin)
end

def transition_counter_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var probe = p2smart.transition_counter_probe(out_pin, in_pin, 100, 8, 2000)
    assert(probe["ok"])
    assert(probe["transition"]["count"] == 8)
    assert(probe["counter"]["delta"] > 0)
    reset_pair(out_pin, in_pin)
end

def async_serial_loopback(out_pin, in_pin)
    reset_pair(out_pin, in_pin)
    var values = [0x00, 0x55, 0xa5, 0xff]
    var probe = p2smart.async_serial_probe(out_pin, in_pin, values, 100, 115200, 8)
    assert(probe["ok"])
    assert(probe["values"] == values)
    assert(probe["count"] == values.size())
    for item : probe["results"]
        assert(item["ok"])
        assert(type(item["event"]) == "int")
    end
    reset_pair(out_pin, in_pin)
end

def dac_adc_loopback(out_pin, in_pin)
    var probe = p2smart.dac_adc_probe(out_pin, in_pin, 0, 255, 5000, 0)
    print("P2_SMOKE_ADC_VALUES " + str(out_pin) + "_" + str(in_pin) + " " + str(probe["low_raw"]) + " " + str(probe["high_raw"]))
    assert(probe["ok"])
    assert(type(probe["low_raw"]) == "int")
    assert(type(probe["high_raw"]) == "int")
    assert(type(probe["delta"]) == "int")
    assert(type(probe["abs_delta"]) == "int")
    reset_pair(out_pin, in_pin)
end

var pairs = p2smart.default_jumper_pairs()

print("P2_SMOKE_CASE dac_adc_probe_0_1")
var analog_probe = p2smart.dac_adc_probe(0, 1, 0, 255, 5000, 0)
print("P2_SMOKE_ADC_PROBE " + str(analog_probe["ok"]) + " " + str(analog_probe["low_raw"]) + " " + str(analog_probe["high_raw"]) + " " + str(analog_probe["delta"]) + " " + str(analog_probe["abs_delta"]))
assert(analog_probe["ok"])
assert(type(analog_probe["low_raw"]) == "int")
assert(type(analog_probe["high_raw"]) == "int")
assert(type(analog_probe["delta"]) == "int")
assert(type(analog_probe["abs_delta"]) == "int")
reset_pair(0, 1)

print("P2_SMOKE_CASE dac_adc_sampled_probe_0_1")
var sampled_analog_probe = p2smart.dac_adc_sampled_probe(0, 1, 0, 255, 5000, 0, 4, 250)
print("P2_SMOKE_ADC_SAMPLED " + str(sampled_analog_probe["ok"]) + " " + str(sampled_analog_probe["low"]["avg"]) + " " + str(sampled_analog_probe["high"]["avg"]) + " " + str(sampled_analog_probe["delta"]) + " " + str(sampled_analog_probe["abs_delta"]) + " " + sampled_analog_probe["polarity"])
assert(sampled_analog_probe["ok"])
assert(sampled_analog_probe["sample_count"] == 4)
assert(sampled_analog_probe["low"]["count"] == 4)
assert(sampled_analog_probe["high"]["count"] == 4)
assert(type(sampled_analog_probe["delta"]) == "int")
assert(type(sampled_analog_probe["abs_delta"]) == "int")
assert(!sampled_analog_probe["polarity_verified"])
assert(!sampled_analog_probe["calibrated_voltage"])
reset_pair(0, 1)

print("P2_SMOKE_CASE dac_variant_adc_sampled_probe_0_1")
var sampled_variant_probe = p2smart.dac_variant_adc_sampled_probe(0, 1, 0, 255, 256, "600r_2v", "dither_rnd", 5000, 0, 4, 250)
print("P2_SMOKE_ADC_VARIANT_SAMPLED " + str(sampled_variant_probe["ok"]) + " " + str(sampled_variant_probe["low"]["avg"]) + " " + str(sampled_variant_probe["high"]["avg"]) + " " + str(sampled_variant_probe["delta"]) + " " + str(sampled_variant_probe["abs_delta"]) + " " + sampled_variant_probe["polarity"])
assert(sampled_variant_probe["ok"])
assert(sampled_variant_probe["sample_count"] == 4)
assert(sampled_variant_probe["low"]["count"] == 4)
assert(sampled_variant_probe["high"]["count"] == 4)
assert(sampled_variant_probe["resistor"] == "600r_2v")
assert(sampled_variant_probe["dither"] == "dither_rnd")
assert(type(sampled_variant_probe["delta"]) == "int")
assert(type(sampled_variant_probe["abs_delta"]) == "int")
assert(!sampled_variant_probe["polarity_verified"])
assert(!sampled_variant_probe["calibrated_voltage"])
reset_pair(0, 1)

print("P2_SMOKE_CASE adc_variant_dac_sampled_probe_0_1")
var sampled_adc_variant_probe = p2smart.adc_variant_dac_sampled_probe(0, 1, 0, 255, "3x", "adc_ext", 256, 5000, 0, 4, 250)
print("P2_SMOKE_ADC_NAMED_SAMPLED " + str(sampled_adc_variant_probe["ok"]) + " " + str(sampled_adc_variant_probe["low"]["avg"]) + " " + str(sampled_adc_variant_probe["high"]["avg"]) + " " + str(sampled_adc_variant_probe["delta"]) + " " + str(sampled_adc_variant_probe["abs_delta"]) + " " + sampled_adc_variant_probe["source"] + " " + sampled_adc_variant_probe["family"] + " " + sampled_adc_variant_probe["polarity"])
assert(sampled_adc_variant_probe["ok"])
assert(sampled_adc_variant_probe["sample_count"] == 4)
assert(sampled_adc_variant_probe["low"]["count"] == 4)
assert(sampled_adc_variant_probe["high"]["count"] == 4)
assert(sampled_adc_variant_probe["source"] == "3x")
assert(sampled_adc_variant_probe["family"] == "adc_ext")
assert(sampled_adc_variant_probe["sample_ticks"] == 256)
assert(type(sampled_adc_variant_probe["delta"]) == "int")
assert(type(sampled_adc_variant_probe["abs_delta"]) == "int")
assert(!sampled_adc_variant_probe["polarity_verified"])
assert(!sampled_adc_variant_probe["calibrated_voltage"])
reset_pair(0, 1)

print("P2_SMOKE_CASE adc_dac_variants_sampled_probe_0_1")
var sampled_both_variant_probe = p2smart.adc_dac_variants_sampled_probe(0, 1, 0, 255, "10x", "adc_scope", 256, 256, "75r_2v", "plain", 5000, 0, 4, 250)
print("P2_SMOKE_ADC_DAC_VARIANTS_SAMPLED " + str(sampled_both_variant_probe["ok"]) + " " + str(sampled_both_variant_probe["low"]["avg"]) + " " + str(sampled_both_variant_probe["high"]["avg"]) + " " + str(sampled_both_variant_probe["delta"]) + " " + str(sampled_both_variant_probe["abs_delta"]) + " " + sampled_both_variant_probe["source"] + " " + sampled_both_variant_probe["family"] + " " + sampled_both_variant_probe["resistor"] + " " + sampled_both_variant_probe["dither"] + " " + sampled_both_variant_probe["polarity"])
assert(sampled_both_variant_probe["ok"])
assert(sampled_both_variant_probe["sample_count"] == 4)
assert(sampled_both_variant_probe["low"]["count"] == 4)
assert(sampled_both_variant_probe["high"]["count"] == 4)
assert(sampled_both_variant_probe["source"] == "10x")
assert(sampled_both_variant_probe["family"] == "adc_scope")
assert(sampled_both_variant_probe["sample_ticks"] == 256)
assert(sampled_both_variant_probe["resistor"] == "75r_2v")
assert(sampled_both_variant_probe["dither"] == "plain")
assert(type(sampled_both_variant_probe["delta"]) == "int")
assert(type(sampled_both_variant_probe["abs_delta"]) == "int")
assert(!sampled_both_variant_probe["polarity_verified"])
assert(!sampled_both_variant_probe["calibrated_voltage"])
reset_pair(0, 1)

for pair : pairs
    var a = pair[0]
    var b = pair[1]
    print("P2_SMOKE_PAIR " + str(a) + "_" + str(b))
    print("P2_SMOKE_CASE dac_adc_ab")
    dac_adc_loopback(a, b)
    print("P2_SMOKE_CASE dac_adc_ba")
    dac_adc_loopback(b, a)
    print("P2_SMOKE_CASE gpio_ab")
    gpio_loopback(a, b)
    print("P2_SMOKE_CASE gpio_ba")
    gpio_loopback(b, a)
    print("P2_SMOKE_CASE raw_a")
    raw_smartpin_api(a)
    print("P2_SMOKE_CASE raw_b")
    raw_smartpin_api(b)
    print("P2_SMOKE_CASE repository_a")
    repository_mode(a)
    print("P2_SMOKE_CASE repository_b")
    repository_mode(b)
    print("P2_SMOKE_CASE pwm_ab")
    pwm_counter_loopback(a, b)
    print("P2_SMOKE_CASE pwm_ba")
    pwm_counter_loopback(b, a)
    print("P2_SMOKE_CASE pwm_sawtooth_ab")
    pwm_variant_counter_loopback(a, b, "sawtooth")
    print("P2_SMOKE_CASE pwm_sawtooth_ba")
    pwm_variant_counter_loopback(b, a, "sawtooth")
    print("P2_SMOKE_CASE pwm_smps_ab")
    pwm_variant_counter_loopback(a, b, "smps")
    print("P2_SMOKE_CASE pwm_smps_ba")
    pwm_variant_counter_loopback(b, a, "smps")
    print("P2_SMOKE_CASE high_counter_ab")
    high_counter_loopback(a, b)
    print("P2_SMOKE_CASE high_counter_ba")
    high_counter_loopback(b, a)
    print("P2_SMOKE_CASE counter_variant_drive_ab")
    counter_variant_drive_loopback(a, b)
    print("P2_SMOKE_CASE counter_variant_drive_ba")
    counter_variant_drive_loopback(b, a)
    print("P2_SMOKE_CASE nco_ab")
    nco_counter_loopback(a, b)
    print("P2_SMOKE_CASE nco_ba")
    nco_counter_loopback(b, a)
    print("P2_SMOKE_CASE nco_duty_ab")
    nco_duty_counter_loopback(a, b)
    print("P2_SMOKE_CASE nco_duty_ba")
    nco_duty_counter_loopback(b, a)
    print("P2_SMOKE_CASE pulse_ab")
    pulse_counter_loopback(a, b)
    print("P2_SMOKE_CASE pulse_ba")
    pulse_counter_loopback(b, a)
    print("P2_SMOKE_CASE transition_ab")
    transition_counter_loopback(a, b)
    print("P2_SMOKE_CASE transition_ba")
    transition_counter_loopback(b, a)
    print("P2_SMOKE_CASE async_ab")
    async_serial_loopback(a, b)
    print("P2_SMOKE_CASE async_ba")
    async_serial_loopback(b, a)
end

print("P2_SMOKE_STAGE negative")

expect_error(def ()
    p2smart.smart.wrpin(-1, 0)
end)
expect_error(def ()
    p2smart.smart.wxpin(64, 0)
end)
expect_error(def ()
    p2smart.smart.wypin(0, -1)
end)
expect_error(def ()
    p2smart.smart.start(0, -1, 0, 0)
end)
expect_error(def ()
    p2smart.smart.start(0, 0, -1, 0)
end)
expect_error(def ()
    p2smart.smart.start(0, 0, 0, -1)
end)
expect_error(def ()
    p2smart.smart.rdpin(58)
end)
expect_error(def ()
    p2smart.smart.rqpin(62)
end)
expect_error(def ()
    p2smart.gpio_input(-1)
end)
expect_error(def ()
    p2smart.gpio_output(64, nil)
end)
expect_error(def ()
    p2smart.gpio_output(0, 2)
end)
expect_error(def ()
    p2smart.gpio_output(0, nil).write(2)
end)

var status = p2smart.status_info()
if status["build"]["board_has_psram"] != 0
    expect_error(def ()
        p2smart.smart.clear(57)
    end)
end

for pair : pairs
    reset_pair(pair[0], pair[1])
end

print("P2_SMOKE_PASS smartpins_loopback")
