print("P2_SMOKE_BEGIN relop")

def assert_true(status)
    assert(status == true)
end

def assert_false(status)
    assert(status == false)
end

assert_true(0 == 0)
assert_false(0 != 0)
assert_true(0 != 1)
assert_false(0 == 1)
assert_true(0.0 == 0)
assert_false(0.0 != 0)
assert_true(0.0 != 1.0)
assert_false(0.0 == 1.0)
assert_true(41 < 42)
assert_true(42 <= 42)
assert_true(43 > 42)
assert_true(42 >= 42)
assert_false(42 < 42)
assert_false(42 > 42)

assert_true(nil == nil)
assert_false(nil != nil)
assert_true(true != nil)
assert_false(true == nil)
assert_true(nil != false)
assert_false(nil == false)

assert_true(list == list)
assert_false(list == map)
assert_true(map == map)
assert_false(map == list)

assert_true([] == [])
assert_true([true] == [true])
assert_true([[]] == [[]])
assert_false([[]] != [[]])
assert_true([1, 2] != [2, 1])
assert_false([1, 2] == [2, 1])
assert_false([0] == [])
assert_false([] != [])
assert_true([] != nil)
assert_false([] == nil)

assert_true(bytes("AA") == bytes("AA"))
assert_false(bytes("AA") != bytes("AA"))
assert_false(bytes("AA") == bytes("AB"))
assert_true(bytes("AA") != bytes("AB"))
assert_true(bytes() != nil)
assert_false(bytes() == nil)

assert_true({} != nil)
assert_false({} == nil)
assert_true({"a": 1} == {"a": 1})
assert_true({"a": [1, 2]} == {"a": [1, 2]})
assert_true({"a": 1, "b": 2} == {"b": 2, "a": 1})
assert_true({"outer": {"a": 1, "b": 2}} == {"outer": {"b": 2, "a": 1}})
assert_true({"a": nil} == {"a": nil})
assert_false({"a": 1} == {"a": 2})
assert_false({"a": nil} == {})

print("P2_SMOKE_PASS relop")
