print("P2_SMOKE_BEGIN modules")

import string
assert(string.toupper("abc") == "ABC")
assert(string.find("banana", "na") == 2)

import math
assert(math.sqrt(81) == 9)
assert(math.min(5, 2, 9) == 2)
assert(math.max(5, 2, 9) == 9)
assert(math.abs(-42) == 42)
assert(math.floor(2.9) == 2)
assert(math.floor(-2.1) == -3)
assert(math.ceil(2.1) == 3)
assert(math.ceil(-2.9) == -2)
assert(math.round(2.5) == 3)
assert(math.round(-2.5) == -3)
assert(type(math.nan) == "real")
assert(type(math.inf) == "real")
assert(math.isnan(math.nan))
assert(!math.isnan(1))
assert(math.isinf(math.inf))
assert(math.isinf(-math.inf))
assert(!math.isinf(1))
assert(math.sqrt(-1) == nil)
assert(math.log(0) == nil)
assert(math.log(-1) == nil)
assert(math.log10(0) == nil)
assert(math.pow(-2, 0.5) == nil)
assert(math.asin(2) == nil)
assert(math.acos(-2) == nil)
def math_close(a, b, eps)
    return math.abs(a - b) < eps
end
var accel = math.accel_info()
assert(type(accel) == "map")
assert(type(accel["backend"]) == "string")
assert(type(accel["reason"]) == "string")
assert(type(accel["cordic"]) == "bool")
assert(type(accel["p2"]) == "bool")
assert(accel["scale"] == 1000000)
assert(accel["turn"] == 4294967296.0)
assert(accel["sqrt"] == false)
assert(accel["exp"] == false)
assert(accel["log"] == false)
if accel["cordic"]
    assert(accel["backend"] == "p2_cordic")
    assert(accel["sin"])
    assert(accel["cos"])
    assert(accel["tan"])
    assert(accel["atan2"])
    assert(accel["asin"])
    assert(accel["acos"])
else
    assert(accel["backend"] == "berry_fallback")
end
assert(math_close(math.sin(0), 0, 0.0001))
assert(math_close(math.sin(math.pi / 2), 1, 0.0001))
assert(math_close(math.cos(0), 1, 0.0001))
assert(math_close(math.cos(math.pi), -1, 0.0001))
assert(math_close(math.tan(0), 0, 0.0001))
assert(math_close(math.atan(1), math.pi / 4, 0.0001))
assert(math_close(math.atan2(1, 0), math.pi / 2, 0.0001))
assert(math_close(math.asin(1), math.pi / 2, 0.0001))
assert(math_close(math.acos(0), math.pi / 2, 0.0001))
assert(math_close(math.exp(1), math.e, 0.0002))
assert(math_close(math.log(math.e), 1, 0.0002))
assert(math_close(math.log10(100), 2, 0.0002))
assert(math_close(math.pow(2, 0.5), math.sqrt(2), 0.0002))
assert(math_close(math.sinh(0), 0, 0.0001))
assert(math_close(math.cosh(0), 1, 0.0001))
assert(math_close(math.tanh(0), 0, 0.0001))
assert(math_close(math.deg(math.pi), 180, 0.0001))
assert(math_close(math.rad(180), math.pi, 0.0001))

import json
var decoded = json.load('{"a":1,"b":[2,3]}')
assert(decoded["b"][1] == 3)
var encoded = json.dump({"x": 1, "y": [2, 3]})
assert(type(encoded) == "string")
assert(json.load(encoded)["y"][0] == 2)

import bytes
var b = bytes().fromstring("AB")
assert(b.tohex() == "4142")
assert(b.asstring() == "AB")
assert(bytes("1122")[1] == 0x22)

import p2
assert(p2.clock_freq() > 0)
assert(p2.cogid() >= 0)
assert(p2.cogid() < 8)
assert(type(p2.heap_info()) == "map")
assert(type(p2.cog_states()) == "list")
var status = p2.status_info()
assert(type(status) == "map")
assert(status["build"]["profile"] != "")
assert(status["runtime"]["toolchain"] == "Catalina")
assert(status["clock"]["frequency"] > 0)
assert(status["memory"]["hub_total"] == 512 * 1024)
assert(status["memory"]["main_heap_total"] > 0)
assert(status["psram"]["access"] == p2.psram_info()["access"])
assert(type(status["cogs"]) == "list")
assert(status["cogs"].size() == 8)
assert(status["cogs"][p2.cogid()]["current"] == true)
assert(p2.debug_snapshot()["build"]["profile"] == status["build"]["profile"])

run_file("/tests/p2/smoke_p2_api.be")

print("P2_SMOKE_PASS modules")
