print("P2_SMOKE_BEGIN import_all_libs")

import libstore
assert(type(libstore.capabilities) == "function")
assert(type(libstore.capability) == "function")
assert(type(libstore.required_capability_keys) == "function")
assert(type(libstore.audit) == "function")
assert(type(libstore.audit_problems) == "function")
assert(type(libstore.audit_ok) == "function")
assert(libstore.required_capability_keys().find("lazy_sd_source") >= 0)
assert(libstore.required_capability_keys().find("audit_policy") >= 0)
assert(libstore.capability("lazy_sd_source"))
assert(libstore.capability("coverage_metadata"))
assert(libstore.capability("compiled_fallback"))
assert(libstore.capability("psram_source_cache"))
assert(libstore.capability("pasm_storage_policy"))
assert(libstore.capability("audit"))
assert(libstore.capability("missing") == nil)
var lib_audit = libstore.audit()
assert(lib_audit["ok"])
assert(lib_audit["problem_count"] == 0)
assert(lib_audit["problems"].size() == 0)
assert(lib_audit["missing_capability_keys"].size() == 0)
assert(lib_audit["audit_policy"] == "metadata_only_no_sd_scan_or_cache_mutation")
assert(lib_audit["known_count"] == 10)
assert(lib_audit["covered_count"] == 9)
assert(lib_audit["hardware_deferred_count"] == 1)
assert(lib_audit["unknown_coverage_count"] == 0)
assert(lib_audit["pasm_policy"]["storage_root"] == "/berry/pasm")
assert(!lib_audit["pasm_policy"]["execution_supported"])
lib_audit["problems"].push("mutation_probe")
assert(libstore.audit_problems().size() == 0)
assert(libstore.audit_ok())

var expected = [
    "binary_heap",
    "configstore",
    "libstore",
    "math",
    "p2compat",
    "p2ipc",
    "p2mem",
    "p2smart",
    "task",
    "wifi"
]

for name : expected
    assert(libstore.exists(name))
    assert(libstore.source_path(name) != nil)
    var info = libstore.info(name)
    assert(info["exists"])
    assert(info["selected_kind"] == "source")
    assert(info["sd_import_smoke"] == "/tests/p2/smoke_import_all_libs.be")
    assert(info["metadata_smoke"] == "/tests/p2/smoke_module_inventory.be")
    var stats = libstore.source_stats(name)
    assert(stats["exists"])
    assert(info["source_size"] == stats["size"])
    assert(info["source_hash"] == stats["hash"])
    assert(type(info["coverage_status"]) == "string")
    if name == "wifi"
        assert(info["coverage_status"] == "hardware_deferred")
        assert(info["behavior_smoke"] == nil)
    else
        assert(info["coverage_status"] == "covered")
        assert(type(info["behavior_smoke"]) == "string")
    end
end

import binary_heap
assert(type(binary_heap) == "module")
assert(type(binary_heap.capabilities) == "function")
assert(type(binary_heap.capability) == "function")
assert(type(binary_heap.required_capability_keys) == "function")
assert(type(binary_heap.audit) == "function")
assert(type(binary_heap.audit_problems) == "function")
assert(type(binary_heap.audit_ok) == "function")
assert(binary_heap.required_capability_keys().find("sort") >= 0)
assert(binary_heap.required_capability_keys().find("audit_policy") >= 0)
assert(binary_heap.capability("sort"))
assert(binary_heap.capability("make_heap"))
assert(binary_heap.capability("remove_heap"))
assert(binary_heap.capability("heap_copy_commit"))
assert(binary_heap.capability("exception_preserves_input"))
assert(binary_heap.capability("audit"))
assert(binary_heap.capability("missing") == nil)
assert(binary_heap.audit_ok())
assert(binary_heap.audit()["missing_capability_keys"].size() == 0)
assert(binary_heap.audit_problems().size() == 0)
var data = [4, 1, 3]
binary_heap.sort(data, /a b -> a < b)
assert(data == [1, 3, 4])

import configstore
assert(type(configstore) == "module")
assert(configstore.path("demo") == "/berry/config/demo.json")
assert(type(configstore.capabilities) == "function")
assert(type(configstore.capability) == "function")
assert(type(configstore.required_capability_keys) == "function")
assert(type(configstore.audit) == "function")
assert(type(configstore.audit_problems) == "function")
assert(type(configstore.audit_ok) == "function")
assert(configstore.required_capability_keys().find("load_result") >= 0)
assert(configstore.required_capability_keys().find("root") >= 0)
assert(configstore.capability("load_result"))
assert(configstore.capability("save_result"))
assert(configstore.capability("remove_result"))
assert(configstore.capability("list_result"))
assert(configstore.capability("json_null_detection"))
assert(configstore.capability("audit"))
assert(configstore.capability("root") == "/berry/config")
assert(configstore.capability("missing") == nil)
assert(configstore.audit_ok())
assert(configstore.audit()["missing_capability_keys"].size() == 0)
assert(configstore.audit_problems().size() == 0)

import math
assert(type(math) == "module")
assert(type(math.capabilities) == "function")
assert(type(math.capability) == "function")
assert(type(math.required_capability_keys) == "function")
assert(type(math.audit) == "function")
assert(type(math.audit_problems) == "function")
assert(type(math.audit_ok) == "function")
assert(math.required_capability_keys().find("finite_fallbacks") >= 0)
assert(math.required_capability_keys().find("p2_cordic_available") >= 0)
assert(math.required_capability_keys().find("audit_policy") >= 0)
assert(math.sqrt(49) == 7)
assert(math.capability("finite_fallbacks"))
assert(type(math.capability("nan_inf")) == "bool")
assert(math.capability("invalid_domain_nil"))
assert(math.capability("non_number_zero"))
assert(math.capability("constants"))
assert(math.capability("rounding"))
assert(math.capability("minmax"))
assert(math.capability("angle_conversion"))
assert(math.capability("audit"))
assert(math.capability("cordic_sqrt") == false)
assert(math.capability("cordic_exp_log") == false)
assert(math.capability("missing") == nil)
var math_audit = math.audit()
assert(math_audit["ok"])
assert(math_audit["problem_count"] == 0)
assert(math_audit["problems"].size() == 0)
assert(math_audit["missing_capability_keys"].size() == 0)
assert(math_audit["audit_policy"] == "finite_metadata_and_tiny_numeric_self_check")
assert(type(math_audit["backend"]) == "string")
assert(math_audit["finite_fallbacks"])
assert(math_audit["nan_inf"] == math.capability("nan_inf"))
assert(math_audit["invalid_domain_nil"])
assert(math_audit["non_number_zero"])
assert(math_audit["constants"])
assert(math_audit["rounding"])
assert(math_audit["minmax"])
assert(math_audit["angle_conversion"])
math_audit["problems"].push("mutation_probe")
assert(math.audit_problems().size() == 0)
assert(math.audit_ok())

import p2compat
assert(type(p2compat) == "module")
assert(p2compat.status("environment") == p2compat.UNSUPPORTED)
assert(p2compat.status("video_output") == p2compat.UNSUPPORTED)
assert(p2compat.status("usb_hid") == p2compat.UNSUPPORTED)
assert(type(p2compat.child_vm_transfer_policy) == "function")
assert(type(p2compat.child_vm_partition_policy) == "function")
assert(type(p2compat.required_capability_names) == "function")
assert(type(p2compat.required_child_vm_policy_keys) == "function")
assert(p2compat.required_capability_names().find("child_vm_transfer_policy") >= 0)
assert(p2compat.required_capability_names().find("child_vm_partition_policy") >= 0)
assert(p2compat.required_child_vm_policy_keys().find("status_capabilities") >= 0)
var import_child_policy = p2compat.child_vm_transfer_policy()
assert(import_child_policy["primitive_copy"] == p2compat.PARTIAL)
assert(import_child_policy["closure_name_bridge"] == p2compat.STAGED)
assert(import_child_policy["captured_closure_transfer"] == p2compat.UNSUPPORTED)
assert(import_child_policy["live_object_transfer"] == p2compat.UNSUPPORTED)
assert(import_child_policy["copyable_types"].find("int") >= 0)
assert(import_child_policy["rejected_live_types"].find("hardware_resource") >= 0)
assert(!import_child_policy["ownership_transfer"])
assert(p2compat.child_vm_copyable_type("int"))
assert(!p2compat.child_vm_copyable_type("map"))
assert(p2compat.child_vm_rejected_type("hardware_resource"))
assert(!p2compat.child_vm_rejected_type("string"))
var import_partition_policy = p2compat.child_vm_partition_policy()
assert(import_partition_policy["model"] == "runtime_heap_info_partition_policy")
assert(import_partition_policy["sizing_policy"] == "runtime_derived_no_fixed_production_count")
assert(!import_partition_policy["production_count_selected"])
assert(import_partition_policy["retry_policy"] == "stop_routine_priority_work_until_native_partition_allocator_changes")
assert(p2compat.audit()["missing_capability_names"].size() == 0)
assert(p2compat.audit()["missing_child_vm_policy_keys"].size() == 0)
assert(p2compat.audit()["missing_child_vm_partition_policy_keys"].size() == 0)

import p2ipc
assert(type(p2ipc) == "module")
assert(type(p2ipc.Mutex) == "class")
assert(type(p2ipc.capabilities) == "function")
assert(type(p2ipc.capability) == "function")
assert(type(p2ipc.contract) == "function")
assert(type(p2ipc.attention_policy) == "function")
assert(type(p2ipc.required_capability_keys) == "function")
assert(type(p2ipc.required_contract_keys) == "function")
assert(type(p2ipc.audit) == "function")
assert(type(p2ipc.audit_problems) == "function")
assert(type(p2ipc.audit_ok) == "function")
assert(type(p2ipc.self_test_result) == "function")
assert(p2ipc.capabilities()["channel"])
assert(p2ipc.capability("self_test_result"))
assert(p2ipc.capability("self_test_policy") == "bounded_current_vm_cleanup_diagnostic")
assert(p2ipc.capability("contract"))
assert(p2ipc.capability("close_result"))
assert(p2ipc.capability("close_releases_payloads"))
assert(p2ipc.capability("clear_result"))
assert(p2ipc.capability("clear_releases_payloads"))
assert(p2ipc.capability("snapshot_result"))
assert(p2ipc.capability("peek_result"))
assert(p2ipc.capability("shared_buffer_clear_result"))
assert(p2ipc.capability("result_diagnostics"))
assert(p2ipc.capability("payload_contract_results"))
assert(p2ipc.capability("cross_vm") == false)
assert(p2ipc.capability("attention_policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.capability("bounded_attention_wait"))
assert(p2ipc.capability("cross_cog_attention_wakeup") == false)
assert(p2ipc.contract()["model"] == "current_vm_cooperative_ipc")
assert(!p2ipc.contract()["cross_vm"])
assert(p2ipc.contract()["attention_policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.contract()["bounded_attention_wait"])
assert(!p2ipc.contract()["cross_cog_attention_wakeup"])
assert(!p2ipc.contract()["serialization"])
assert(p2ipc.contract()["payload_contract_results"])
assert(p2ipc.contract()["close_releases_payloads"])
assert(p2ipc.contract()["clear_releases_payloads"])
assert(p2ipc.contract()["snapshot_result"])
assert(p2ipc.contract()["peek_result"])
assert(p2ipc.contract()["shared_buffer_clear_result"])
assert(p2ipc.contract()["self_test_result"])
assert(p2ipc.required_capability_keys().find("serialization_policy") >= 0)
assert(p2ipc.required_capability_keys().find("attention_policy") >= 0)
assert(p2ipc.required_capability_keys().find("bounded_attention_wait") >= 0)
assert(p2ipc.required_capability_keys().find("cross_cog_attention_wakeup") >= 0)
assert(p2ipc.required_contract_keys().find("unsupported_reason") >= 0)
assert(p2ipc.required_contract_keys().find("attention_policy") >= 0)
assert(p2ipc.audit_ok())
assert(p2ipc.audit()["ok"])
assert(p2ipc.audit()["missing_capability_keys"].size() == 0)
assert(p2ipc.audit()["missing_contract_keys"].size() == 0)
assert(p2ipc.audit()["bounded_attention_wait"])
assert(!p2ipc.audit()["cross_cog_attention_wakeup"])
assert(p2ipc.audit_problems().size() == 0)
var import_ipc_attention = p2ipc.attention_policy()
assert(import_ipc_attention["bounded_attention_wait"])
assert(!import_ipc_attention["cross_cog_wakeup"])
assert(!import_ipc_attention["channel_wakeup"])
assert(!import_ipc_attention["mailbox_wakeup"])
var import_ipc_self_test = p2ipc.self_test_result(1)
assert(import_ipc_self_test["ok"])
assert(import_ipc_self_test["iterations"] == 1)
assert(import_ipc_self_test["failure_count"] == 0)
assert(p2ipc.capability("missing") == nil)
var import_ch = p2ipc.channel.new(1)
assert(type(import_ch.clear_result) == "function")
var import_send = import_ch.send_result("x")
assert(import_send["ok"])
assert(import_send["payload_contract"])
assert(import_send["current_vm_reference"])
assert(!import_send["serialized"])
assert(!import_send["ownership_transfer"])
assert(type(import_ch.snapshot_result) == "function")
var import_snapshot = import_ch.snapshot_result()
assert(import_snapshot["ok"])
assert(import_snapshot["items"].size() == 1)
assert(import_snapshot["items"][0] == "x")
assert(import_snapshot["payload_contract"])
assert(import_ch.size() == 1)
assert(import_ch.clear_result()["released_payloads"] == 1)
assert(type(import_ch.close_result) == "function")
assert(import_ch.close_result()["ok"])
var import_mb = p2ipc.mailbox.new()
assert(type(import_mb.clear_result) == "function")
var import_put = import_mb.put_result("x")
assert(import_put["ok"])
assert(import_put["payload_contract"])
assert(import_put["current_vm_reference"])
assert(import_put["ownership_policy"] == "caller_keeps_current_vm_object_ownership")
assert(type(import_mb.peek_result) == "function")
var import_peek = import_mb.peek_result()
assert(import_peek["ok"])
assert(import_peek["found"])
assert(import_peek["value"] == "x")
assert(import_mb.ready())
assert(import_mb.clear_result()["released_payload"])
assert(type(import_mb.close_result) == "function")
assert(import_mb.close_result()["ok"])
var import_buf = p2ipc.shared.Buffer(2)
assert(type(import_buf.clear_result) == "function")
assert(import_buf.fill(7))
assert(import_buf.clear_result()["released_bytes"] == 2)

import p2mem
assert(type(p2mem) == "module")
assert(type(p2mem.capabilities) == "function")
assert(type(p2mem.capability) == "function")
assert(type(p2mem.required_capability_keys) == "function")
assert(type(p2mem.audit) == "function")
assert(type(p2mem.audit_problems) == "function")
assert(type(p2mem.audit_ok) == "function")
assert(p2mem.required_capability_keys().find("stats_result") >= 0)
assert(p2mem.required_capability_keys().find("audit_policy") >= 0)
assert(p2mem.capability("stats_result"))
assert(p2mem.capability("modules_result"))
assert(p2mem.capability("module_result"))
assert(p2mem.capability("cache_result"))
assert(p2mem.capability("gc_result"))
assert(p2mem.capability("native_cache_result_wrappers"))
assert(p2mem.capability("native_cache_owner_helpers"))
assert(p2mem.capability("native_module_source_helpers"))
assert(p2mem.capability("invalid_module_name_diagnostics"))
assert(p2mem.capability("snapshot_diagnostics"))
assert(p2mem.capability("audit"))
assert(p2mem.capability("missing") == nil)
assert(p2mem.audit_ok())
assert(p2mem.audit()["audit_policy"] == "metadata_and_name_validation_only_no_cache_mutation")
assert(p2mem.audit()["missing_capability_keys"].size() == 0)
assert(p2mem.audit_problems().size() == 0)
assert(isinstance(p2mem.stats(), map))

import p2smart
assert(type(p2smart) == "module")
assert(type(p2smart.GPIOInput) == "class")
assert(type(p2smart.GPIOOutput) == "class")
assert(type(p2smart.PWM) == "class")
assert(type(p2smart.Quadrature) == "class")
assert(type(p2smart.NCO) == "class")
assert(type(p2smart.Counter) == "class")
assert(type(p2smart.Repository) == "class")
assert(type(p2smart.Pulse) == "class")
assert(type(p2smart.Transition) == "class")
assert(type(p2smart.AsyncSerialPair) == "class")
assert(type(p2smart.SyncSerialPair) == "class")
assert(type(p2smart.ADC) == "class")
assert(type(p2smart.DAC) == "class")
assert(type(p2smart.dac_adc_probe) == "function")
assert(type(p2smart.items_by_status) == "function")
assert(type(p2smart.names) == "function")
assert(type(p2smart.names_by_status) == "function")
assert(type(p2smart.statuses) == "function")
assert(type(p2smart.status_known) == "function")
assert(type(p2smart.status) == "function")
assert(type(p2smart.jumper_pair_checks) == "function")
assert(type(p2smart.required_capability_keys) == "function")
assert(type(p2smart.raw_smartpin_reserved_pin_policy) == "function")
assert(type(p2smart.audit) == "function")
assert(type(p2smart.audit_problems) == "function")
assert(type(p2smart.audit_ok) == "function")
assert(p2smart.capabilities()["async_serial_zero_byte"] == "verified")
assert(p2smart.capabilities()["gpio_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["async_serial_probe"] == "diagnostic")
assert(p2smart.capabilities()["async_serial_drain"] == "diagnostic")
assert(p2smart.capabilities()["async_serial_drain_probe"] == "diagnostic")
assert(p2smart.capabilities()["async_serial_buffer_policy"] == "diagnostic")
assert(p2smart.capabilities()["gpio_loopback_probe"] == "diagnostic")
assert(p2smart.capabilities()["jumper_pair_checks"] == "diagnostic")
assert(p2smart.jumper_pair_checks().find("async_serial_drain") >= 0)
assert(p2smart.capabilities()["raw_smartpin_probe"] == "diagnostic")
assert(p2smart.capabilities()["raw_smartpin_reserved_pin_policy"] == "diagnostic")
assert(p2smart.capabilities()["raw_smartpin_reserved_pin_rejection"] == "staged")
assert(p2smart.capabilities()["normal_pin_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["counter_sample_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["counter_variant_sample_probe"] == "diagnostic")
assert(p2smart.capabilities()["high_counter_probe"] == "diagnostic")
assert(p2smart.capabilities()["repository_write_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["repository_read_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["repository_probe"] == "diagnostic")
assert(p2smart.capabilities()["quadrature_sample_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["quadrature_sample_probe"] == "diagnostic")
assert(p2smart.capabilities()["adc_sample_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["adc_variant_sample_probe"] == "diagnostic")
assert(p2smart.capabilities()["adc_dac_sampled_probe"] == "verified")
assert(p2smart.capabilities()["adc_variant_dac_sampled_probe"] == "diagnostic")
assert(p2smart.capabilities()["dac_set_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["dac_variant_adc_probe"] == "diagnostic")
assert(p2smart.capabilities()["dac_variant_adc_sampled_probe"] == "verified")
assert(p2smart.capabilities()["adc_dac_variants_sampled_probe"] == "diagnostic")
assert(p2smart.capabilities()["adc_dac_delta_policy"] == "diagnostic")
assert(p2smart.capabilities()["pwm_duty_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["pwm_counter_probe"] == "diagnostic")
assert(p2smart.capabilities()["pwm_variant_counter_probe"] == "diagnostic")
assert(p2smart.capabilities()["nco_increment_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["nco_counter_probe"] == "diagnostic")
assert(p2smart.capabilities()["nco_duty_diagnostics"] == "verified")
assert(p2smart.capabilities()["nco_duty_counter_probe"] == "verified")
assert(p2smart.capabilities()["nco_duty_waveform_probe"] == "verified")
assert(p2smart.capabilities()["pulse_trigger_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["pulse_counter_probe"] == "diagnostic")
assert(p2smart.capabilities()["transition_trigger_diagnostics"] == "diagnostic")
assert(p2smart.capabilities()["transition_counter_probe"] == "diagnostic")
assert(p2smart.capabilities()["sync_serial_receive"] == "verified")
assert(p2smart.capabilities()["sync_serial_result_diagnostics"] == "verified")
assert(p2smart.capabilities()["sync_serial_transfer_diagnostics"] == "verified")
assert(p2smart.capabilities()["adc_dac_delta"] == "unverified")
assert(p2smart.required_capability_keys().find("async_serial_drain_probe") >= 0)
assert(p2smart.required_capability_keys().find("sync_serial_receive") >= 0)
assert(p2smart.status_report()["capabilities"]["async_serial_paced_exchange"] == "verified")
assert(p2smart.status_known("verified"))
assert(!p2smart.status_known("missing"))
assert(p2smart.status("async_serial_zero_byte") == "verified")
assert(p2smart.status("sync_serial_receive") == "verified")
assert(p2smart.status("raw_smartpin_reserved_pin_rejection") == "staged")
assert(p2smart.status("usb_pair") == "unsupported")
assert(p2smart.status("missing") == nil)
var raw_reserved_policy = p2smart.raw_smartpin_reserved_pin_policy()
assert(raw_reserved_policy["capability"] == "raw_smartpin_reserved_pin_rejection")
assert(raw_reserved_policy["status"] == "staged")
assert(raw_reserved_policy["policy"] == "deferred_current_image_hangs")
assert(raw_reserved_policy["attempt_result"] == "hung_before_begin_marker")
var async_buffer_policy = p2smart.async_serial_buffer_policy()
assert(!async_buffer_policy["supported"])
assert(async_buffer_policy["status"] == "unsupported")
assert(async_buffer_policy["policy"] == "unsupported_no_fifo_buffer")
assert(async_buffer_policy["safe_receive_helpers"].find("read_available_results") >= 0)
assert(async_buffer_policy["safe_receive_helpers"].find("read_available") >= 0)
var adc_dac_delta_policy = p2smart.adc_dac_delta_policy()
assert(!adc_dac_delta_policy["supported"])
assert(adc_dac_delta_policy["status"] == "unverified")
assert(adc_dac_delta_policy["policy"] == "unverified_no_calibrated_threshold")
assert(isinstance(p2smart.names(), list))
assert(isinstance(p2smart.names_by_status("verified"), list))
assert(p2smart.names_by_status("verified").find("adc_dac_sampled_probe") >= 0)
assert(p2smart.names_by_status("verified").find("dac_variant_adc_sampled_probe") >= 0)
assert(p2smart.names_by_status("diagnostic").find("adc_variant_dac_sampled_probe") >= 0)
assert(p2smart.names_by_status("diagnostic").find("adc_dac_variants_sampled_probe") >= 0)
assert(p2smart.audit_ok())
assert(p2smart.audit()["ok"])
assert(p2smart.audit()["missing_capability_keys"].size() == 0)
assert(p2smart.audit()["jumper_pair_checks_ok"])
assert(p2smart.audit_problems().size() == 0)
var p2smart_verified = p2smart.items_by_status("verified")
var p2smart_found_sync_result_diag = false
var p2smart_found_sync_transfer_diag = false
for name : p2smart_verified
    if name == "sync_serial_result_diagnostics"
        p2smart_found_sync_result_diag = true
    end
    if name == "sync_serial_transfer_diagnostics"
        p2smart_found_sync_transfer_diag = true
    end
end
assert(p2smart_found_sync_result_diag)
assert(p2smart_found_sync_transfer_diag)

import task
assert(type(task) == "module")
var task_max = task.info()["max_tasks"]
assert(task_max == 16 || task_max == 32)
assert(task.capabilities()["cooperative"])
assert(task.capabilities()["spin"])
assert(task.capabilities()["event_diagnostics"])
assert(task.capabilities()["self_test_result"])
assert(task.capabilities()["self_test_policy"] == "bounded_current_vm_cleanup_diagnostic")
assert(!task.capabilities()["preemptive"])
assert(type(task.capability) == "function")
if type(task.contract) == "function"
    var task_contract = task.contract()
    assert(task_contract["scheduler_policy"] == "current_vm_callback_step")
    assert(task_contract["max_tasks"] == task_max)
    assert(task_contract["sharing_policy"] == "current_vm_objects_only")
    assert(!task_contract["preemptive"])
    assert(!task_contract["cross_vm_serialization"])
end
if type(task.required_capability_keys) == "function"
    assert(task.required_capability_keys().find("scheduler_policy") >= 0)
    assert(task.required_capability_keys().find("spin2_lifecycle_names") >= 0)
    assert(task.required_capability_keys().find("self_test_result") >= 0)
end
if type(task.required_contract_keys) == "function"
    assert(task.required_contract_keys().find("sharing_policy") >= 0)
    assert(task.required_contract_keys().find("cross_cog_wakeup") >= 0)
end
assert(type(task.primitive_capability) == "function")
assert(task.capability("cooperative"))
assert(task.capability("self_test_result"))
assert(task.capability("self_test_policy") == "bounded_current_vm_cleanup_diagnostic")
assert(task.capability("preemptive") == false)
assert(task.capability("max_tasks") == task_max)
assert(task.capability("missing") == nil)
if type(task.required_primitive_capability_keys) == "function"
    assert(task.required_primitive_capability_keys().find("queue_get_result") >= 0)
    assert(task.required_primitive_capability_keys().find("timer_remaining_result") >= 0)
end
assert(task.primitive_capability("queue_get_result"))
assert(task.primitive_capability("timer_restart_result"))
assert(task.primitive_capability("timer_remaining_result"))
assert(task.primitive_capability("missing") == nil)
assert(type(task.self_test_result) == "function")
var import_task_self_test = task.self_test_result(1)
assert(import_task_self_test["ok"])
assert(import_task_self_test["iterations"] == 1)
assert(import_task_self_test["failure_count"] == 0)
assert(import_task_self_test["active_after"] == 0)
assert(import_task_self_test["events_after"] == 0)

import wifi
assert(type(wifi) == "module")
assert(type(wifi.capabilities) == "function")
assert(type(wifi.capability) == "function")
assert(type(wifi.default_config) == "function")
assert(type(wifi.audit) == "function")
assert(type(wifi.audit_problems) == "function")
assert(type(wifi.audit_ok) == "function")
assert(wifi.STATUS[255] == "no_shield")
assert(wifi.capability("transport") == "spi")
assert(wifi.capability("hardware") == "wifinina_airlift")
assert(wifi.capability("hardware_deferred"))
assert(wifi.capability("request_requires_init"))
assert(wifi.capability("import_init_noop"))
assert(wifi.capability("default_config"))
assert(wifi.capability("audit"))
assert(wifi.capability("missing") == nil)
assert(type(wifi.required_capability_keys) == "function")
assert(wifi.required_capability_keys().find("transport") >= 0)
assert(wifi.required_capability_keys().find("audit_policy") >= 0)
var wifi_cfg = wifi.default_config()
assert(wifi_cfg["sck"] == 16)
assert(wifi_cfg["mosi"] == 17)
assert(wifi_cfg["miso"] == 18)
assert(wifi_cfg["cs"] == 19)
assert(wifi_cfg["busy"] == 20)
assert(wifi_cfg["reset"] == 21)
assert(wifi_cfg["irq"] == 22)
assert(wifi_cfg["khz"] == 1000)
assert(wifi_cfg["mode"] == 0)
wifi_cfg["sck"] = 99
assert(wifi.default_config()["sck"] == 16)
var wifi_audit = wifi.audit()
assert(wifi_audit["ok"])
assert(wifi_audit["problem_count"] == 0)
assert(wifi_audit["problems"].size() == 0)
assert(wifi_audit["missing_capability_keys"].size() == 0)
assert(wifi_audit["transport"] == "spi")
assert(wifi_audit["hardware_deferred"])
assert(wifi_audit["request_requires_init"])
assert(wifi_audit["import_init_noop"])
assert(wifi_audit["audit_policy"] == "metadata_only_no_spi_transaction")
wifi_audit["problems"].push("mutation_probe")
assert(wifi.audit_problems().size() == 0)
assert(wifi.audit_ok())

print("P2_SMOKE_PASS import_all_libs")
