print("P2_SMOKE_BEGIN pasm_policy_min")

import p2
import string

def check(cond, label)
    if !cond
        print("P2_SMOKE_FAIL pasm_policy_min", label)
    end
    assert(cond)
end

def contains(list_value, wanted)
    return string.find(str(list_value), "'" + wanted + "'") >= 0
end

check(type(p2.asm.capabilities) == "function", "capabilities_function")
check(type(p2.asm.capability) == "function", "capability_function")
check(type(p2.asm.fixture_call) == "function", "fixture_call_function")
check(type(p2.asm.fixture_add) == "function", "fixture_add_function")
check(type(p2.asm.abi) == "function", "abi_function")
check(type(p2.asm.abi_value) == "function", "abi_value_function")
check(type(p2.asm.audit) == "function", "audit_function")
check(type(p2.asm.required_capability_keys) == "function", "required_caps_function")
check(type(p2.asm.required_abi_keys) == "function", "required_abi_function")

var caps = p2.asm.capabilities()
var required_caps = p2.asm.required_capability_keys()
check(required_caps.find("function_bridge_policy") != nil, "required_function_bridge")
check(required_caps.find("fixture_call_policy") != nil, "required_fixture_call")
check(required_caps.find("fixture_call_ops") != nil, "required_fixture_ops")
check(required_caps.find("inline_assembler_policy") != nil, "required_inline")
check(required_caps.find("unsafe_gate") != nil, "required_unsafe_gate")
required_caps.push("caller_mutated")
check(p2.asm.required_capability_keys().find("caller_mutated") == nil, "required_caps_snapshot")

check(caps["safe_intrinsics"], "safe_intrinsics")
check(caps["sd_load"], "sd_load")
check(caps["raw_cognew"], "raw_cognew")
check(caps["marker_probe"], "marker_probe")
check(caps["fixture_call"], "fixture_call")
check(caps["fixture_call_policy"] == "fixed_named_operation_fixture_mailbox_only", "fixture_call_policy")
check(contains(caps["fixture_call_ops"], "add"), "fixture_op_add")
check(contains(caps["fixture_call_ops"], "sub"), "fixture_op_sub")
caps["fixture_call_ops"].push("caller_mutated")
check(!contains(p2.asm.capability("fixture_call_ops"), "caller_mutated"), "fixture_ops_snapshot")
check(p2.asm.capability("fixture_call") == true, "capability_fixture_call")
check(p2.asm.capability("fixture_call_policy") == caps["fixture_call_policy"], "capability_fixture_call_policy")
check(!caps["arbitrary_sd_launch_supported"], "arbitrary_sd_launch_false")
check(caps["arbitrary_blob_policy"] == "unsupported_exact_marker_fixture_only", "arbitrary_blob_policy")
check(p2.asm.capability("arbitrary_blob_policy") == caps["arbitrary_blob_policy"], "capability_arbitrary_policy")
check(!caps["function_bridge"], "function_bridge_false")
check(caps["function_bridge_policy"] == "unsupported_no_calling_convention", "function_bridge_policy")
check(p2.asm.capability("function_bridge_policy") == caps["function_bridge_policy"], "capability_function_policy")
check(p2.asm.capability("function_bridge") == false, "capability_function_false")
check(string.find(caps["function_bridge_reason"], "argument marshalling") != nil, "function_bridge_reason")
check(!caps["inline_assembler"], "inline_false")
check(caps["inline_assembler_policy"] == "unsupported_no_parser_or_safety_contract", "inline_policy")
check(string.find(caps["inline_assembler_reason"], "assembly parser") != nil, "inline_reason")
check(!caps["unsafe_asm"], "unsafe_false")
check(caps["unsafe_gate"] == "BE_P2_ENABLE_UNSAFE_ASM", "unsafe_gate")
check(p2.asm.capability("unsafe_gate") == caps["unsafe_gate"], "capability_unsafe_gate")
check(caps["unsafe_default"] == false, "unsafe_default")
check(caps["unsafe_module"] == "none", "unsafe_module")
check(p2.asm.capability("missing") == nil, "capability_missing")
check(p2.asm.capability(nil) == nil, "capability_nil")

var abi = p2.asm.abi()
var required_abi = p2.asm.required_abi_keys()
check(required_abi.find("function_bridge_required") != nil, "required_abi_function_bridge")
check(required_abi.find("fixture_call_policy") != nil, "required_abi_fixture_call")
check(required_abi.find("fixture_call_ops") != nil, "required_abi_fixture_ops")
check(required_abi.find("inline_assembler_required") != nil, "required_abi_inline")
check(required_abi.find("unsafe_gate") != nil, "required_abi_unsafe_gate")
required_abi.push("caller_mutated")
check(p2.asm.required_abi_keys().find("caller_mutated") == nil, "required_abi_snapshot")

check(abi["status"] == "marker_and_fixture_call_only", "abi_status")
check(p2.asm.abi_value("status") == abi["status"], "abi_value_status")
check(abi["fixture_call_abi"], "abi_fixture_call")
check(abi["fixture_call_policy"] == caps["fixture_call_policy"], "abi_fixture_call_policy")
check(contains(abi["fixture_call_ops"], "xor"), "abi_fixture_op_xor")
check(p2.asm.abi_value("fixture_call_policy") == abi["fixture_call_policy"], "abi_value_fixture_call_policy")
check(contains(p2.asm.abi_value("fixture_call_ops"), "or"), "abi_value_fixture_ops")
check(abi["arbitrary_blob_abi"] == false, "abi_arbitrary_false")
check(abi["arbitrary_blob_policy"] == caps["arbitrary_blob_policy"], "abi_arbitrary_policy")
check(p2.asm.abi_value("arbitrary_blob_policy") == abi["arbitrary_blob_policy"], "abi_value_arbitrary_policy")
check(abi["function_bridge_abi"] == false, "abi_function_false")
check(abi["function_bridge_policy"] == caps["function_bridge_policy"], "abi_function_policy")
check(p2.asm.abi_value("function_bridge_policy") == abi["function_bridge_policy"], "abi_value_function_policy")
check(string.find(abi["function_bridge_required"], "return values") != nil, "abi_function_required")
check(abi["inline_assembler_abi"] == false, "abi_inline_false")
check(abi["inline_assembler_policy"] == caps["inline_assembler_policy"], "abi_inline_policy")
check(string.find(abi["inline_assembler_required"], "register clobbers") != nil, "abi_inline_required")
check(abi["unsafe_gate"] == caps["unsafe_gate"], "abi_unsafe_gate")
check(p2.asm.abi_value("unsafe_gate") == abi["unsafe_gate"], "abi_value_unsafe_gate")
check(abi["unsafe_default"] == false, "abi_unsafe_default")
check(abi["unsafe_module"] == "none", "abi_unsafe_module")
check(p2.asm.abi_value("missing") == nil, "abi_value_missing")
check(p2.asm.abi_value(nil) == nil, "abi_value_nil")

var audit = p2.asm.audit()
check(p2.asm.audit_ok(), "audit_ok_helper")
check(p2.asm.audit_problems().size() == 0, "audit_problems_helper")
check(isinstance(audit, map), "audit_map")
check(audit["ok"], "audit_ok")
check(audit["problem_count"] == 0, "audit_problem_count")
check(audit["missing_capability_keys"].size() == 0, "audit_missing_caps")
check(audit["missing_abi_keys"].size() == 0, "audit_missing_abi")
check(audit["fixture_call_policy"] == caps["fixture_call_policy"], "audit_fixture_call_policy")
check(audit["function_bridge_policy_match"], "audit_function_policy_match")
check(audit["inline_assembler_policy_match"], "audit_inline_policy_match")
check(audit["unsafe_gate_match"], "audit_unsafe_gate_match")
audit["problems"].push("caller_mutated")
check(p2.asm.audit()["problems"].size() == 0, "audit_snapshot")

var fixture = p2.asm.fixture_add(123, 456)
check(isinstance(fixture, map), "fixture_map")
check(fixture["ok"], "fixture_ok")
check(fixture["done"], "fixture_done")
check(fixture["result"] == 579, "fixture_result")
check(fixture["operation"] == "add", "fixture_add_operation")
check(fixture["cog_seen_matches"], "fixture_cog_seen")
check(fixture["stopped"], "fixture_stopped")
check(fixture["policy"] == caps["fixture_call_policy"], "fixture_policy")

var sub = p2.asm.fixture_call("sub", 123, 23)
check(sub["ok"], "fixture_sub_ok")
check(sub["result"] == 100, "fixture_sub_result")
check(sub["operation"] == "sub", "fixture_sub_operation")

var xor = p2.asm.fixture_call("xor", 85, 15)
check(xor["ok"], "fixture_xor_ok")
check(xor["result"] == 90, "fixture_xor_result")

var band = p2.asm.fixture_call("and", 85, 15)
check(band["ok"], "fixture_and_ok")
check(band["result"] == 5, "fixture_and_result")

var bor = p2.asm.fixture_call("or", 80, 15)
check(bor["ok"], "fixture_or_ok")
check(bor["result"] == 95, "fixture_or_result")

print("P2_SMOKE_PASS pasm_policy_min")
