print("P2_SMOKE_BEGIN p2ipc")

import p2ipc

assert(type(p2ipc) == "module")
assert(type(p2ipc.channel.new) == "function")
assert(type(p2ipc.mailbox.new) == "function")
assert(type(p2ipc.shared.Buffer) == "class")
assert(type(p2ipc.mutex.Mutex) == "class")

caps = p2ipc.capabilities()
assert(caps["current_vm"])
assert(!caps["cross_vm"])
assert(caps["channel"])
assert(caps["mailbox"])
assert(caps["mutex"])
assert(caps["shared_buffer"])
assert(caps["payload_contract_results"])
assert(caps["task_wait_integration"])
assert(caps["task_wait_channel"])
assert(caps["task_wait_mailbox"])
assert(caps["snapshot_result"])
assert(caps["peek_result"])
assert(caps["clear_releases_payloads"])
assert(caps["close_releases_payloads"])
assert(caps["self_test_result"])
assert(p2ipc.capability("snapshot_result"))
assert(p2ipc.capability("task_wait_integration"))
assert(p2ipc.capability("peek_result"))
assert(p2ipc.capability("missing") == nil)
assert(p2ipc.required_capability_keys().find("payload_contract_results") >= 0)
assert(p2ipc.required_capability_keys().find("task_wait_integration") >= 0)
assert(p2ipc.required_capability_keys().find("task_wait_channel") >= 0)
assert(p2ipc.required_capability_keys().find("task_wait_mailbox") >= 0)
assert(p2ipc.required_capability_keys().find("attention_policy") >= 0)
assert(p2ipc.required_capability_keys().find("bounded_attention_wait") >= 0)
assert(p2ipc.required_capability_keys().find("cross_cog_attention_wakeup") >= 0)
assert(p2ipc.required_contract_keys().find("unsupported_reason") >= 0)
assert(p2ipc.required_contract_keys().find("attention_policy") >= 0)

contract = p2ipc.contract()
assert(contract["model"] == "current_vm_cooperative_ipc")
assert(contract["current_vm"])
assert(!contract["cross_vm"])
assert(!contract["cross_cog_wakeup"])
assert(contract["attention_policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(contract["bounded_attention_wait"])
assert(!contract["cross_cog_attention_wakeup"])
assert(!contract["serialization"])
assert(!contract["ownership_transfer"])
assert(contract["payload_contract_results"])
assert(contract["task_wait_integration"])
assert(contract["task_wait_channel"])
assert(contract["task_wait_mailbox"])
assert(contract["snapshot_result"])
assert(contract["peek_result"])
assert(contract["clear_releases_payloads"])
assert(contract["close_releases_payloads"])
assert(contract["self_test_result"])
assert(type(p2ipc.contract_value) == "function")
assert(p2ipc.contract_value("model") == "current_vm_cooperative_ipc")
assert(p2ipc.contract_value("current_vm"))
assert(p2ipc.contract_value("cross_vm") == false)
assert(p2ipc.contract_value("task_wait_integration"))
assert(p2ipc.contract_value("attention_policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.contract_value("serialization_policy") == "unsupported_current_vm_references_only")
assert(p2ipc.contract_value("missing") == nil)
assert(p2ipc.contract_value(nil) == nil)

assert(p2ipc.audit_ok())
audit = p2ipc.audit()
assert(audit["ok"])
assert(audit["problem_count"] == 0)
assert(audit["problems"].size() == 0)
assert(audit["missing_capability_keys"].size() == 0)
assert(audit["missing_contract_keys"].size() == 0)
assert(audit["bounded_attention_wait"])
assert(audit["task_wait_integration"])
assert(audit["task_wait_channel"])
assert(audit["task_wait_mailbox"])
assert(!audit["cross_cog_attention_wakeup"])

attention = p2ipc.attention_policy()
assert(attention["policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(attention["bounded_attention_wait"])
assert(attention["wait_helper"] == "p2.cog.wait_attention_result")
assert(!attention["cross_cog_wakeup"])
assert(!attention["channel_wakeup"])
assert(!attention["mailbox_wakeup"])
assert(attention["current_vm_only"])
assert(type(p2ipc.attention_policy_value) == "function")
assert(p2ipc.attention_policy_value("policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.attention_policy_value("bounded_attention_wait"))
assert(p2ipc.attention_policy_value("cross_cog_wakeup") == false)
assert(p2ipc.attention_policy_value("channel_wakeup") == false)
assert(p2ipc.attention_policy_value("mailbox_wakeup") == false)
assert(p2ipc.attention_policy_value("current_vm_only"))
assert(p2ipc.attention_policy_value("missing") == nil)
assert(p2ipc.attention_policy_value(nil) == nil)

self_test = p2ipc.self_test_result(2)
assert(self_test["ok"])
assert(self_test["iterations"] == 2)
assert(self_test["failure_count"] == 0)
assert(self_test["failures"].size() == 0)

ch = p2ipc.channel.new(2)
assert(ch.info()["kind"] == "Channel")
assert(ch._task_kind == "p2ipc_channel")
assert(ch.send_result("a")["ok"])
assert(ch.send_result(nil)["ok"])
full = ch.send_result("c")
assert(!full["ok"])
assert(full["error"] == "full")
snapshot = ch.snapshot_result()
assert(snapshot["ok"])
assert(snapshot["items"].size() == 2)
assert(snapshot["items"][0] == "a")
assert(snapshot["items"][1] == nil)
assert(snapshot["payload_contract"])
assert(snapshot["current_vm_reference"])
snapshot["items"].clear()
assert(ch.size() == 2)
recv_a = ch.recv_result()
assert(recv_a["ok"])
assert(recv_a["found"])
assert(recv_a["value"] == "a")
recv_nil = ch.recv_result()
assert(recv_nil["ok"])
assert(recv_nil["found"])
assert(recv_nil["value"] == nil)
recv_empty = ch.recv_result()
assert(recv_empty["ok"])
assert(!recv_empty["found"])
assert(ch.send_result("cleanup")["ok"])
clear_ch = ch.clear_result()
assert(clear_ch["ok"])
assert(clear_ch["released_payloads"] == 1)
close_ch = ch.close_result()
assert(close_ch["ok"])
assert(close_ch["closed"])
assert(ch.send_result("closed")["error"] == "closed")

mb = p2ipc.mailbox.new()
assert(mb.info()["kind"] == "Mailbox")
assert(mb._task_kind == "p2ipc_mailbox")
assert(mb.put_result(nil)["ok"])
peek_nil = mb.peek_result()
assert(peek_nil["ok"])
assert(peek_nil["found"])
assert(peek_nil["value"] == nil)
assert(peek_nil["payload_type"] == "nil")
assert(mb.ready())
got_nil = mb.get_result()
assert(got_nil["ok"])
assert(got_nil["found"])
assert(got_nil["value"] == nil)
assert(mb.put_result("held")["ok"])
peek = mb.peek_result()
assert(peek["ok"])
assert(peek["found"])
assert(peek["value"] == "held")
assert(mb.ready())
clear_mb = mb.clear_result()
assert(clear_mb["ok"])
assert(clear_mb["released_payload"])
close_mb = mb.close_result()
assert(close_mb["ok"])
assert(close_mb["closed"])
assert(mb.put_result("closed")["error"] == "closed")

buf = p2ipc.shared.Buffer(4)
assert(buf.fill_result(7)["ok"])
assert(buf.read(0) == 7)
clear_buf = buf.clear_result()
assert(clear_buf["ok"])
assert(clear_buf["released_bytes"] == 4)
assert(buf.read(0) == 0)

mx = p2ipc.mutex.new()
lock_result = mx.lock_result()
assert(lock_result["ok"])
assert(lock_result["locked"])
unlock_result = mx.unlock_result()
assert(unlock_result["ok"])
assert(unlock_result["unlocked"])
close_mx = mx.close_result()
assert(close_mx["ok"])
assert(close_mx["closed"])

print("P2_SMOKE_PASS p2ipc")
