print("P2_SMOKE_BEGIN p2compat")

import p2compat

assert(p2compat.supported("sd_filesystem"))
assert(p2compat.supported("board_profile_policy"))

var board_policy = p2compat.board_profile_policy()
assert(board_policy["model"] == "explicit_board_profile_policy")
assert(type(board_policy["board"]) == "string")
assert(type(board_policy["profile"]) == "string")
assert(type(board_policy["memory_profile"]) == "string")
assert(board_policy["reserved_pin_policy"] == "board_profile_reserved_pins_enforced")
assert(board_policy["unsupported_build_policy"] == "raise_loud_or_report_unsupported")
assert(board_policy["normal_toolchain"] == "catalina")
assert(board_policy["normal_catalina_dir"] == "../Catalina")
assert(board_policy["normal_serial_port"] == "/dev/ttyUSB0")
assert(board_policy["status_capabilities"].find("board_profile_policy") >= 0)
assert(board_policy["safe_jumper_pins"].find(7) >= 0)
assert(board_policy["reserved_pin_ranges"].size() >= 2)

assert(p2compat.board_profile_value("profile") == board_policy["profile"])
assert(p2compat.board_profile_value("normal_catalina_dir") == "../Catalina")
assert(p2compat.board_profile_value("missing") == nil)
var ranges = p2compat.board_profile_value("reserved_pin_ranges")
ranges[0]["name"] = "mutated"
assert(p2compat.board_profile_value("reserved_pin_ranges")[0]["name"] != "mutated")
var pins = p2compat.board_profile_value("safe_jumper_pins")
pins.push(99)
assert(p2compat.board_profile_value("safe_jumper_pins").find(99) == nil)
assert(p2compat.board_pin_allowed(0))
assert(p2compat.board_pin_policy(0)["reason"] == "ok")
assert(!p2compat.board_pin_allowed(58))
assert(p2compat.board_pin_policy(58)["reason"] == "sd")
assert(!p2compat.board_pin_allowed(63))
assert(p2compat.board_pin_policy(63)["reason"] == "serial")
if board_policy["psram_enabled"]
    assert(!p2compat.board_pin_allowed(40))
    assert(p2compat.board_pin_policy(40)["reason"] == "psram")
end
assert(!p2compat.board_pin_allowed(64))
assert(p2compat.board_pin_policy(64)["reason"] == "pin_out_of_range")

var audit = p2compat.audit()
assert(audit["ok"])
assert(audit["board_profile_policy_match"])
assert(audit["missing_board_profile_policy_keys"].size() == 0)

var partition_policy = p2compat.child_vm_partition_policy()
assert(partition_policy["model"] == "runtime_heap_info_partition_policy")
assert(partition_policy["source"] == "p2.heap_info")
assert(type(partition_policy["partition_bytes"]) == "int")
assert(partition_policy["partition_bytes"] > 0)
assert(partition_policy["capacity"] >= 1)
assert(partition_policy["free_capacity"] >= 0)
assert(partition_policy["free_capacity"] <= partition_policy["capacity"])
assert(partition_policy["current"] == -1)
assert(partition_policy["usable_for_child_calls"])
assert(partition_policy["sizing_policy"] == "runtime_derived_no_fixed_production_count")
assert(!partition_policy["production_count_selected"])
assert(partition_policy["retry_policy"] == "stop_routine_priority_work_until_native_partition_allocator_changes")
assert(partition_policy["real_cog_policy"] == "unsupported_until_isolated_vm_cog_runtime_safe")
assert(partition_policy["status_capabilities"].find("child_vm_partition_policy") >= 0)
assert(p2compat.child_vm_partition_value("partition_bytes") == partition_policy["partition_bytes"])
assert(p2compat.child_vm_partition_value("retry_policy") == "stop_routine_priority_work_until_native_partition_allocator_changes")
assert(p2compat.child_vm_partition_value("missing") == nil)

var audit_after_partition = p2compat.audit()
assert(audit_after_partition["child_vm_partition_policy_match"])
assert(audit_after_partition["missing_child_vm_partition_policy_keys"].size() == 0)

print("P2_SMOKE_PASS p2compat")
