print("P2_SMOKE_BEGIN p2_api")

import p2

def expect_error(fn)
    var caught = false
    try
        fn()
    except .. as e, m
        caught = true
    end
    assert(caught)
end

var status = p2.status_info()
var led = status["build"]["led0_pin"]
print("P2_SMOKE_STEP p2_api status")

assert(type(p2.clock) == "module")
assert(type(p2.cog) == "module")
assert(type(p2.lock) == "module")
assert(type(p2.pin) == "module")
assert(type(p2.cordic) == "module")
assert(type(p2.math) == "module")
assert(type(p2.rng) == "module")
assert(type(p2.smart) == "module")
assert(type(p2.asm) == "module")
assert(type(p2.debug) == "module")
assert(p2.smart.normal == 0)
assert(type(p2.smart.invert_a) == "int")
assert(str(p2.smart.invert_a) == "-2147483648")
assert(p2.smart.invert_a < 0)
assert(p2.smart.pwm_triangle == 0x10)
assert(p2.smart.count_rises == 0x1c)
assert(p2.smart.adc == 0x30)
assert(p2.smart.async_rx == 0x3e)
assert(p2.smart.dac_990r_3v == 0x140000)

assert(p2.clock.freq() == p2.clock_freq())
assert(p2.clock.mode() == p2.clock_mode())
assert(type(p2.clock.set) == "function")
assert(type(p2.clock.hubset) == "function")
assert(type(p2.clock.waitcnt) == "function")
assert(type(p2.clock.cnt()) == "int")
assert(type(p2.clock.cnth()) == "int")
p2.clock.waitx(1)
p2.clock.waitus(0)
p2.clock.waitms(0)
p2.clock.waitsec(0)
print("P2_SMOKE_STEP p2_api clock")

var cog = p2.cog.id()
assert(cog == p2.cogid())
assert(cog >= 0 && cog < 8)
assert(type(p2.cog.stop) == "function")
assert(type(p2.cog.attention) == "function")
assert(type(p2.cog.wait_attention) == "function")
assert(type(p2.cog.wait_attention_result) == "function")
assert(type(p2.attention_wait_result) == "function")
assert(p2.cog.check(cog) != 0)
p2.cog.attention(0)
assert(type(p2.cog.poll_attention()) == "int")
var attention_mask = 1 << cog
p2.cog.poll_attention()
p2.cog.attention(attention_mask)
var attention_seen = p2.cog.poll_attention()
assert((attention_seen & attention_mask) != 0)
var attention_timeout = p2.cog.wait_attention_result(0)
assert(!attention_timeout["ok"])
assert(attention_timeout["timed_out"])
assert(attention_timeout["mask"] == 0)
assert(attention_timeout["timeout_us"] == 0)
p2.cog.attention(attention_mask)
var attention_result = p2.cog.wait_attention_result(1000)
assert(attention_result["ok"])
assert(!attention_result["timed_out"])
assert((attention_result["mask"] & attention_mask) != 0)
assert(attention_result["timeout_us"] == 1000)
assert(type(attention_result["elapsed_us"]) == "int")
assert(type(attention_result["polls"]) == "int")
p2.cog.attention(attention_mask)
var attention_wait_mask = p2.cog.wait_attention()
assert((attention_wait_mask & attention_mask) != 0)

var lock = p2.lock.new()
var lock_try = p2.lock.("try")
assert(type(p2.lock.new) == "function")
assert(type(p2.lock.ret) == "function")
assert(type(lock_try) == "function")
assert(type(p2.lock.release) == "function")
assert(type(p2.lock.check) == "function")
if lock >= 0
    var got = lock_try(lock)
    assert(type(got) == "int")
    if got != 0
        p2.lock.release(lock)
    end
    assert(type(p2.lock.check(lock)) == "int")
    p2.lock.ret(lock)
end
print("P2_SMOKE_STEP p2_api cog_lock")

p2.pin.dir_high(led)
p2.pin.low(led)
assert(p2.pin.read(led) == 0)
p2.pin.write(led, 1)
assert(p2.pin.read(led) == 1)
p2.pin.write(led, false)
assert(p2.pin.read(led) == 0)
p2.pin.write(led, true)
assert(p2.pin.read(led) == 1)
p2.pin.high(led)
assert(p2.pin.read(led) == 1)
p2.pin.toggle(led)
p2.clock.waitus(10)
assert(p2.pin.read(led) == 0)
p2.pin.toggle(led)
p2.clock.waitus(10)
assert(p2.pin.read(led) == 1)
p2.pin.dir_low(led)
p2.clock.waitus(10)
p2.pin.float(led)
print("P2_SMOKE_STEP p2_api gpio")

var xypol = p2.cordic.xypol(3, 4)
var polxy = p2.cordic.polxy(1, 0)
var rotxy = p2.cordic.rotxy(1, 0, 0)
assert(type(xypol) == "map")
assert(type(xypol["r"]) == "int")
assert(type(xypol["t"]) == "int")
assert(type(polxy) == "map")
assert(type(polxy["x"]) == "int")
assert(type(polxy["y"]) == "int")
assert(type(rotxy) == "map")
assert(type(rotxy["x"]) == "int")
assert(type(rotxy["y"]) == "int")
assert(p2.math.isqrt(81) == 9)
assert(p2.math.isqrt(0) == 0)
assert(p2.math.muldiv64(6, 7, 3) == 14)
assert(p2.math.rev(0) == 0)
assert(p2.math.encod(8) == 3)
assert(type(p2.rng.rnd()) == "int")
assert(type(p2.asm.getrnd()) == "int")
assert(type(p2.asm.getct()) == "int")
p2.asm.waitx(1)
print("P2_SMOKE_STEP p2_api math_asm")

var debug_snapshot = p2.debug.snapshot()
var debug_heap = p2.debug.heap()
var debug_gc = p2.debug.gc()
var debug_cogs = p2.debug.cogs()
var debug_memory = p2.debug.memory_map()
var debug_caps = p2.debug.capabilities()
assert(debug_caps["snapshot"])
assert(debug_caps["heap"])
assert(debug_caps["gc"])
assert(debug_caps["cogs"])
assert(debug_caps["memory_map"])
assert(debug_caps["pins"])
assert(debug_caps["smartpin"])
assert(debug_caps["registers"])
assert(!debug_caps["breakpoints"])
assert(!debug_caps["trace_controls"])
assert(!debug_caps["source_stack_traces"])
assert(!debug_caps["native_error_detail"])
assert(!debug_caps["module_cache_internals"])
assert(!debug_caps["task_internals"])
assert(!debug_caps["lock_internals"])
assert(!debug_caps["channel_internals"])
assert(!debug_caps["pasm_single_step"])
assert(debug_caps["policy"] == "query_snapshots_only_no_breakpoints_or_trace_controls")
assert(p2.debug.capability("snapshot"))
assert(!p2.debug.capability("breakpoints"))
assert(p2.debug.capability("policy") == "query_snapshots_only_no_breakpoints_or_trace_controls")
assert(p2.debug.capability("missing") == nil)
assert(p2.debug.capability(nil) == nil)
assert(debug_snapshot["build"]["led0_pin"] == led)
assert(type(debug_heap["current"]) == "int")
assert(type(debug_gc["after"]) == "int")
assert(size(debug_cogs) == 8)
assert(debug_cogs[cog]["id"] == cog)
assert(type(debug_memory["hub_total"]) == "int")
var debug_pins = p2.debug.pins()
assert(size(debug_pins) == 64)
assert(debug_pins[led]["pin"] == led)
assert(type(debug_pins[led]["reserved"]) == "bool")
assert(type(debug_pins[led]["input"]) == "bool")
var debug_pin = p2.debug.pin(led)
assert(debug_pin["pin"] == led)
assert(type(debug_pin["reserved"]) == "bool")
assert(type(debug_pin["direction"]) == "string")
var debug_smart = p2.debug.smartpin(led)
assert(debug_smart["pin"] == led)
assert(type(debug_smart["rdpin"]) == "int")
assert(type(debug_smart["rqpin"]) == "int")
var debug_registers = p2.debug.registers()
assert(debug_registers["cog"] == cog)
assert(debug_registers["readable"])
assert(type(debug_registers["ct_low"]) == "int")
assert(type(debug_registers["ct_high"]) == "int")
var debug_registers_explicit = p2.debug.registers(cog)
assert(debug_registers_explicit["cog"] == cog)
assert(debug_registers_explicit["readable"])
assert(type(debug_registers_explicit["ptra"]) == "int")
assert(type(debug_registers_explicit["dira"]) == "int")
print("P2_SMOKE_STEP p2_api debug")

expect_error(def ()
    p2.clock.waitx(-1)
end)
expect_error(def ()
    p2.clock.waitus(-1)
end)
expect_error(def ()
    p2.clock.waitms(-1)
end)
expect_error(def ()
    p2.clock.waitsec(-1)
end)
expect_error(def ()
    p2.clock.set(-1, p2.clock.freq())
end)
expect_error(def ()
    p2.clock.set(p2.clock.mode(), -1)
end)
expect_error(def ()
    p2.clock.hubset(-1)
end)
expect_error(def ()
    p2.asm.waitx(-1)
end)
expect_error(def ()
    p2.asm.hubset(-1)
end)
expect_error(def ()
    p2.math.rev(-1)
end)
expect_error(def ()
    p2.math.isqrt(-1)
end)
expect_error(def ()
    p2.math.muldiv64(-1, 1, 1)
end)
expect_error(def ()
    p2.math.muldiv64(1, -1, 1)
end)
expect_error(def ()
    p2.math.muldiv64(1, 1, -1)
end)
expect_error(def ()
    p2.math.encod(-1)
end)
expect_error(def ()
    p2.cordic.rotxy(1, 0, -1)
end)
expect_error(def ()
    p2.cordic.polxy(-1, 0)
end)
expect_error(def ()
    p2.cordic.polxy(1, -1)
end)
expect_error(def ()
    p2.debug.pin(-1)
end)
expect_error(def ()
    p2.debug.smartpin(-1)
end)
expect_error(def ()
    p2.debug.registers(-1)
end)
expect_error(def ()
    p2.debug.registers(8)
end)
expect_error(def ()
    p2.cog.check(-1)
end)
expect_error(def ()
    p2.cog.check(8)
end)
expect_error(def ()
    p2.cog.stop(-1)
end)
expect_error(def ()
    p2.cog.stop(8)
end)
expect_error(def ()
    p2.cog.stop(p2.cog.id())
end)
expect_error(def ()
    p2.cog.attention(-1)
end)
expect_error(def ()
    p2.cog.wait_attention_result(-1)
end)
expect_error(def ()
    p2.lock.check(-1)
end)
expect_error(def ()
    p2.lock.check(16)
end)
expect_error(def ()
    lock_try(-1)
end)
expect_error(def ()
    lock_try(16)
end)
expect_error(def ()
    p2.lock.release(-1)
end)
expect_error(def ()
    p2.lock.release(16)
end)
expect_error(def ()
    p2.lock.ret(-1)
end)
expect_error(def ()
    p2.lock.ret(16)
end)
expect_error(def ()
    p2.pin.read(-1)
end)
expect_error(def ()
    p2.pin.read(64)
end)
expect_error(def ()
    p2.pin.read(58)
end)
expect_error(def ()
    p2.pin.read(62)
end)
expect_error(def ()
    p2.pin.write(led, nil)
end)
expect_error(def ()
    p2.pin.write(led, "1")
end)
expect_error(def ()
    p2.pin.write(-1, 1)
end)
expect_error(def ()
    p2.pin.write(64, 1)
end)
expect_error(def ()
    p2.pin.dir_low(-1)
end)
expect_error(def ()
    p2.pin.dir_high(64)
end)
expect_error(def ()
    p2.pin.low(-1)
end)
expect_error(def ()
    p2.pin.high(64)
end)
expect_error(def ()
    p2.pin.toggle(-1)
end)
expect_error(def ()
    p2.pin.float(64)
end)
if status["build"]["board_has_psram"] != 0
    expect_error(def ()
        p2.pin.read(57)
    end)
    expect_error(def ()
        p2.pin.write(57, 1)
    end)
    expect_error(def ()
        p2.pin.dir_high(57)
    end)
    expect_error(def ()
        p2.pin.float(57)
    end)
end
expect_error(def ()
    p2.smart.wrpin(-1, 0)
end)
expect_error(def ()
    p2.smart.wxpin(64, 0)
end)
expect_error(def ()
    p2.smart.wxpin(led, -1)
end)
expect_error(def ()
    p2.smart.wypin(led, -1)
end)
expect_error(def ()
    p2.smart.rdpin(-1)
end)
expect_error(def ()
    p2.smart.rqpin(64)
end)
expect_error(def ()
    p2.smart.start(led, p2.smart.normal, -1, 0)
end)
expect_error(def ()
    p2.smart.start(led, p2.smart.normal, 0, -1)
end)
expect_error(def ()
    p2.smart.clear(-1)
end)
print("P2_SMOKE_STEP p2_api negative")

p2.smart.wrpin(led, 0)
p2.smart.wrpin(led, p2.smart.invert_a + p2.smart.normal)
p2.smart.wrpin(led, 0)
p2.smart.wxpin(led, 0)
p2.smart.wypin(led, 0)
p2.smart.akpin(led)
assert(type(p2.smart.rdpin(led)) == "int")
assert(type(p2.smart.rqpin(led)) == "int")
p2.smart.clear(led)
print("P2_SMOKE_STEP p2_api smart")

print("P2_SMOKE_PASS p2_api")
