print("P2_SMOKE_BEGIN p2ipc")

import p2ipc

assert(type(p2ipc) == "module")
assert(type(p2ipc.channel.new) == "function")
assert(type(p2ipc.mailbox.new) == "function")
assert(type(p2ipc.shared.Buffer) == "class")
assert(type(p2ipc.mutex.Mutex) == "class")

caps = p2ipc.capabilities()
assert(caps["current_vm"])
assert(!caps["cross_vm"])
assert(caps["channel"])
assert(caps["mailbox"])
assert(caps["mutex"])
assert(caps["shared_buffer"])
assert(caps["payload_contract_results"])
assert(caps["payload_result"])
assert(caps["payload_copyable_probe"])
assert(caps["payload_copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(caps["task_wait_integration"])
assert(caps["task_wait_channel"])
assert(caps["task_wait_mailbox"])
assert(caps["snapshot_result"])
assert(caps["peek_result"])
assert(caps["clear_releases_payloads"])
assert(caps["close_releases_payloads"])
assert(caps["lifecycle_result"])
assert(caps["resource_lifecycle_result"])
assert(caps["readiness_result"])
assert(caps["channel_ready_result"])
assert(caps["mailbox_ready_result"])
assert(caps["self_test_result"])
assert(p2ipc.capability("snapshot_result"))
assert(p2ipc.capability("task_wait_integration"))
assert(p2ipc.capability("peek_result"))
assert(p2ipc.capability("payload_result"))
assert(p2ipc.capability("missing") == nil)
assert(p2ipc.required_capability_keys().find("payload_contract_results") >= 0)
assert(p2ipc.required_capability_keys().find("payload_result") >= 0)
assert(p2ipc.required_capability_keys().find("payload_copyable_probe") >= 0)
assert(p2ipc.required_capability_keys().find("payload_copy_policy") >= 0)
assert(p2ipc.required_capability_keys().find("task_wait_integration") >= 0)
assert(p2ipc.required_capability_keys().find("task_wait_channel") >= 0)
assert(p2ipc.required_capability_keys().find("task_wait_mailbox") >= 0)
assert(p2ipc.required_capability_keys().find("lifecycle_result") >= 0)
assert(p2ipc.required_capability_keys().find("resource_lifecycle_result") >= 0)
assert(p2ipc.required_capability_keys().find("readiness_result") >= 0)
assert(p2ipc.required_capability_keys().find("channel_ready_result") >= 0)
assert(p2ipc.required_capability_keys().find("mailbox_ready_result") >= 0)
assert(p2ipc.required_capability_keys().find("attention_policy") >= 0)
assert(p2ipc.required_capability_keys().find("bounded_attention_wait") >= 0)
assert(p2ipc.required_capability_keys().find("cross_cog_attention_wakeup") >= 0)
assert(p2ipc.required_contract_keys().find("unsupported_reason") >= 0)
assert(p2ipc.required_contract_keys().find("attention_policy") >= 0)
assert(p2ipc.required_contract_keys().find("payload_result") >= 0)
assert(p2ipc.required_contract_keys().find("payload_copyable_probe") >= 0)
assert(p2ipc.required_contract_keys().find("payload_copy_policy") >= 0)

contract = p2ipc.contract()
assert(contract["model"] == "current_vm_cooperative_ipc")
assert(contract["current_vm"])
assert(!contract["cross_vm"])
assert(!contract["cross_cog_wakeup"])
assert(contract["attention_policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(contract["bounded_attention_wait"])
assert(!contract["cross_cog_attention_wakeup"])
assert(!contract["serialization"])
assert(!contract["ownership_transfer"])
assert(contract["payload_contract_results"])
assert(contract["payload_result"])
assert(contract["payload_copyable_probe"])
assert(contract["payload_copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(contract["task_wait_integration"])
assert(contract["task_wait_channel"])
assert(contract["task_wait_mailbox"])
assert(contract["lifecycle_result"])
assert(contract["resource_lifecycle_result"])
assert(contract["readiness_result"])
assert(contract["channel_ready_result"])
assert(contract["mailbox_ready_result"])
assert(contract["snapshot_result"])
assert(contract["peek_result"])
assert(contract["clear_releases_payloads"])
assert(contract["close_releases_payloads"])
assert(contract["self_test_result"])
assert(type(p2ipc.contract_value) == "function")
assert(p2ipc.contract_value("model") == "current_vm_cooperative_ipc")
assert(p2ipc.contract_value("current_vm"))
assert(p2ipc.contract_value("cross_vm") == false)
assert(p2ipc.contract_value("task_wait_integration"))
assert(p2ipc.contract_value("attention_policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.contract_value("serialization_policy") == "unsupported_current_vm_references_only")
assert(p2ipc.contract_value("payload_result"))
assert(p2ipc.contract_value("missing") == nil)
assert(p2ipc.contract_value(nil) == nil)

payload = p2ipc.payload_result("abc")
assert(payload["ok"])
assert(payload["present"])
assert(payload["value"] == "abc")
assert(payload["payload_contract"])
assert(payload["current_vm_reference"])
assert(!payload["serialized"])
assert(!payload["ownership_transfer"])
assert(payload["payload_type"] == "string")
assert(payload["copyable_policy_available"])
assert(payload["cross_vm_copyable"])
assert(payload["copyable_kind"] == "string")
assert(payload["copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
payload_live = p2ipc.payload_result([1, 2])
assert(payload_live["payload_contract"])
assert(payload_live["payload_type"] == "instance")
assert(isinstance(payload_live["value"], list))
assert(payload_live["copyable_policy_available"])
assert(!payload_live["cross_vm_copyable"])
assert(payload_live["copyable_kind"] == "list")

assert(p2ipc.audit_ok())
audit = p2ipc.audit()
assert(audit["ok"])
assert(audit["problem_count"] == 0)
assert(audit["problems"].size() == 0)
assert(audit["missing_capability_keys"].size() == 0)
assert(audit["missing_contract_keys"].size() == 0)
assert(audit["bounded_attention_wait"])
assert(audit["payload_result"])
assert(audit["payload_copyable_probe"])
assert(audit["payload_copy_policy"] == "use_p2.vm_copyable_for_child_vm_boundaries")
assert(audit["task_wait_integration"])
assert(audit["task_wait_channel"])
assert(audit["task_wait_mailbox"])
assert(audit["lifecycle_result"])
assert(audit["resource_lifecycle_result"])
assert(audit["readiness_result"])
assert(audit["channel_ready_result"])
assert(audit["mailbox_ready_result"])
assert(!audit["cross_cog_attention_wakeup"])

attention = p2ipc.attention_policy()
assert(attention["policy"] == "native_bounded_wait_available_not_wired_to_ipc")
assert(attention["bounded_attention_wait"])
assert(attention["wait_helper"] == "p2.cog.wait_attention_result")
assert(!attention["cross_cog_wakeup"])
assert(!attention["channel_wakeup"])
assert(!attention["mailbox_wakeup"])
assert(attention["current_vm_only"])
assert(type(p2ipc.attention_policy_value) == "function")
assert(p2ipc.attention_policy_value("policy") == "native_bounded_wait_available_not_wired_to_ipc")
assert(p2ipc.attention_policy_value("bounded_attention_wait"))
assert(p2ipc.attention_policy_value("cross_cog_wakeup") == false)
assert(p2ipc.attention_policy_value("channel_wakeup") == false)
assert(p2ipc.attention_policy_value("mailbox_wakeup") == false)
assert(p2ipc.attention_policy_value("current_vm_only"))
assert(p2ipc.attention_policy_value("missing") == nil)
assert(p2ipc.attention_policy_value(nil) == nil)

self_test = p2ipc.self_test_result(2)
assert(self_test["ok"])
assert(self_test["iterations"] == 2)
assert(self_test["failure_count"] == 0)
assert(self_test["failures"].size() == 0)

ch = p2ipc.channel.new(2)
assert(ch.info()["kind"] == "Channel")
assert(ch._task_kind == "p2ipc_channel")
ch_life = ch.lifecycle_result()
assert(ch_life["ok"])
assert(ch_life["kind"] == "Channel")
assert(ch_life["usable"])
assert(!ch_life["closed"])
assert(ch_life["pending_payloads"] == 0)
assert(ch_life["holds_lock_resource"])
assert(!ch_life["ownership_transfer"])
assert(p2ipc.lifecycle_result(ch)["kind"] == "Channel")
ch_empty_ready = ch.ready_result()
assert(ch_empty_ready["ok"])
assert(!ch_empty_ready["ready"])
assert(ch_empty_ready["mode"] == "recv")
assert(ch_empty_ready["can_send"])
assert(!ch_empty_ready["can_recv"])
assert(ch.send_result("a")["ok"])
assert(ch.send_result(nil)["ok"])
ch_life = ch.lifecycle_result()
assert(ch_life["pending_payloads"] == 2)
ch_full_recv_ready = ch.ready_result("recv")
assert(ch_full_recv_ready["ok"])
assert(ch_full_recv_ready["ready"])
assert(ch_full_recv_ready["can_recv"])
assert(!ch_full_recv_ready["can_send"])
ch_full_send_ready = ch.ready_result("send")
assert(ch_full_send_ready["ok"])
assert(!ch_full_send_ready["ready"])
assert(ch_full_send_ready["mode"] == "send")
ch_put_alias_ready = ch.ready_result("put")
assert(ch_put_alias_ready["ok"])
assert(!ch_put_alias_ready["ready"])
assert(ch_put_alias_ready["mode"] == "send")
ch_bad_ready = ch.ready_result("bad")
assert(!ch_bad_ready["ok"])
assert(ch_bad_ready["error"] == "invalid_mode")
full = ch.send_result("c")
assert(!full["ok"])
assert(full["error"] == "full")
snapshot = ch.snapshot_result()
assert(snapshot["ok"])
assert(snapshot["items"].size() == 2)
assert(snapshot["items"][0] == "a")
assert(snapshot["items"][1] == nil)
assert(snapshot["payload_contract"])
assert(snapshot["current_vm_reference"])
snapshot["items"].clear()
assert(ch.size() == 2)
recv_a = ch.recv_result()
assert(recv_a["ok"])
assert(recv_a["found"])
assert(recv_a["value"] == "a")
recv_nil = ch.recv_result()
assert(recv_nil["ok"])
assert(recv_nil["found"])
assert(recv_nil["value"] == nil)
recv_empty = ch.recv_result()
assert(recv_empty["ok"])
assert(!recv_empty["found"])
assert(ch.send_result("cleanup")["ok"])
clear_ch = ch.clear_result()
assert(clear_ch["ok"])
assert(clear_ch["released_payloads"] == 1)
close_ch = ch.close_result()
assert(close_ch["ok"])
assert(close_ch["closed"])
ch_life = ch.lifecycle_result()
assert(ch_life["closed"])
assert(!ch_life["usable"])
assert(!ch_life["holds_lock_resource"])
ch_closed_ready = ch.ready_result("recv")
assert(!ch_closed_ready["ok"])
assert(ch_closed_ready["error"] == "closed")
assert(ch.send_result("closed")["error"] == "closed")

mb = p2ipc.mailbox.new()
assert(mb.info()["kind"] == "Mailbox")
assert(mb._task_kind == "p2ipc_mailbox")
mb_life = mb.lifecycle_result()
assert(mb_life["ok"])
assert(mb_life["kind"] == "Mailbox")
assert(mb_life["usable"])
assert(mb_life["pending_payloads"] == 0)
mb_empty_ready = mb.ready_result()
assert(mb_empty_ready["ok"])
assert(!mb_empty_ready["ready"])
assert(mb_empty_ready["mode"] == "get")
assert(mb_empty_ready["can_put"])
assert(!mb_empty_ready["can_get"])
assert(mb.put_result(nil)["ok"])
mb_life = mb.lifecycle_result()
assert(mb_life["ready"])
assert(mb_life["pending_payloads"] == 1)
mb_full_get_ready = mb.ready_result("get")
assert(mb_full_get_ready["ok"])
assert(mb_full_get_ready["ready"])
assert(mb_full_get_ready["can_get"])
assert(!mb_full_get_ready["can_put"])
mb_full_put_ready = mb.ready_result("put")
assert(mb_full_put_ready["ok"])
assert(!mb_full_put_ready["ready"])
assert(mb_full_put_ready["mode"] == "put")
mb_send_alias_ready = mb.ready_result("send")
assert(mb_send_alias_ready["ok"])
assert(!mb_send_alias_ready["ready"])
assert(mb_send_alias_ready["mode"] == "put")
mb_bad_ready = mb.ready_result("bad")
assert(!mb_bad_ready["ok"])
assert(mb_bad_ready["error"] == "invalid_mode")
peek_nil = mb.peek_result()
assert(peek_nil["ok"])
assert(peek_nil["found"])
assert(peek_nil["value"] == nil)
assert(peek_nil["payload_type"] == "nil")
assert(mb.ready())
got_nil = mb.get_result()
assert(got_nil["ok"])
assert(got_nil["found"])
assert(got_nil["value"] == nil)
assert(mb.put_result("held")["ok"])
peek = mb.peek_result()
assert(peek["ok"])
assert(peek["found"])
assert(peek["value"] == "held")
assert(mb.ready())
clear_mb = mb.clear_result()
assert(clear_mb["ok"])
assert(clear_mb["released_payload"])
close_mb = mb.close_result()
assert(close_mb["ok"])
assert(close_mb["closed"])
mb_life = mb.lifecycle_result()
assert(mb_life["closed"])
assert(!mb_life["usable"])
assert(!mb_life["holds_lock_resource"])
mb_closed_ready = mb.ready_result("get")
assert(!mb_closed_ready["ok"])
assert(mb_closed_ready["error"] == "closed")
assert(mb.put_result("closed")["error"] == "closed")

buf = p2ipc.shared.Buffer(4)
buf_life = buf.lifecycle_result()
assert(buf_life["ok"])
assert(buf_life["kind"] == "Buffer")
assert(buf_life["usable"])
assert(!buf_life["holds_lock_resource"])
assert(buf.fill_result(7)["ok"])
assert(buf.read(0) == 7)
clear_buf = buf.clear_result()
assert(clear_buf["ok"])
assert(clear_buf["released_bytes"] == 4)
assert(buf.read(0) == 0)

mx = p2ipc.mutex.new()
mx_life = mx.lifecycle_result()
assert(mx_life["ok"])
assert(mx_life["kind"] == "Mutex")
assert(mx_life["usable"])
assert(mx_life["holds_lock_resource"])
lock_result = mx.lock_result()
assert(lock_result["ok"])
assert(lock_result["locked"])
unlock_result = mx.unlock_result()
assert(unlock_result["ok"])
assert(unlock_result["unlocked"])
close_mx = mx.close_result()
assert(close_mx["ok"])
assert(close_mx["closed"])
mx_life = mx.lifecycle_result()
assert(mx_life["closed"])
assert(!mx_life["usable"])
assert(!mx_life["holds_lock_resource"])

print("P2_SMOKE_PASS p2ipc")
