import p2

print("clock")
print(p2.clock_freq())
print(p2.clock_mode())

print("counter")
var start = p2.ticks()
p2.wait_ticks(p2.clock_freq() / 10)
print(p2.ticks() - start)
var ticks = p2.ticks64()
print("ticks64", ticks["high"], ticks["low"])

print("math")
print(p2.random())
print(p2.reverse_bits(1))
print(p2.encode(0x10))
print(p2.isqrt(10000))
print(p2.muldiv64(1000, 2000, 25))
var rot = p2.rotxy(1000, 0, 0)
print("rotxy", rot["x"], rot["y"])
var polar = p2.xypol(1000, 0)
print("xypol", polar["r"], polar["t"])
var xy = p2.polxy(1000, 0)
print("polxy", xy["x"], xy["y"])

print("cogs")
print(p2.cogid())
print(p2.cog_id())
var states = p2.cog_states()
print("cog states", states.size(), states[p2.cogid()])
print(p2.cog_check(p2.cogid()))
print(p2.cog_stack_bytes(p2.cogid()))

print("attention")
p2.attention_signal(1 << p2.cogid())
print(p2.attention_poll())
print("p2 hardware helpers done")
